import { actionLogsFor, esc, fmtDateTime, fmtMinutes, statusLabel, titleCase } from "./helpers.js";

function resultSummary(field, actionId) {
  const config = field.config || {}; const details = field.type === "measurement" ? config.defaultUnitId || "unit" : field.type === "score" ? `/${config.maximum ?? 100}` : field.type === "choice" ? `${config.options?.length || 0} options` : field.type === "text" ? (config.multiline ? "multiline" : "short text") : "0–100";
  return `<div class="samt-result-item"><div><strong>${esc(field.label)}</strong><small>${esc(titleCase(field.type))} · ${esc(String(details))}${field.required ? " · Required" : " · Optional"}</small></div><div class="samt-row-actions"><span class="samt-badge subtle">v${Number(field.definitionVersion) || 1} · ${Number(field.position || 0) + 1}</span><button class="samt-button ghost small" data-action="move-result-up" data-id="${esc(field.id)}" data-action-id="${esc(actionId)}" aria-label="Move Result Field up">↑</button><button class="samt-button ghost small" data-action="move-result-down" data-id="${esc(field.id)}" data-action-id="${esc(actionId)}" aria-label="Move Result Field down">↓</button><button class="samt-button ghost small" data-action="edit-result" data-id="${esc(field.id)}" data-action-id="${esc(actionId)}">Edit</button><button class="samt-button ghost small danger" data-action="remove-result" data-id="${esc(field.id)}" data-action-id="${esc(actionId)}">Remove</button></div></div>`;
}

function actionCard(state, action) {
  const logs = actionLogsFor(state, action.id); return `<article class="samt-card samt-entity-card"><div class="samt-card-head"><div><a class="samt-entity-link" href="#/actions/${encodeURIComponent(action.id)}"><h2>${esc(action.name)}</h2></a><span class="samt-badge ${action.direction === "avoid" ? "warn" : "good"}">${esc(action.direction === "avoid" ? "Avoid" : "Do")}</span></div><span class="samt-status">${esc(statusLabel(action.status))}</span></div><p class="samt-muted">${esc(action.description || "No description")}</p><div class="samt-stat-line"><span>${esc(action.completion?.method || "time")} · ${action.completion?.method === "quantity" ? `${action.completion.target} required` : `${action.completion?.minimumMinutes ?? 0} min minimum`}</span><span>${logs.length} log${logs.length === 1 ? "" : "s"}</span><span>${fmtMinutes(logs.reduce((sum, log) => sum + Number(log.durationMinutes || 0), 0))}</span></div><div class="samt-card-actions"><button class="samt-button primary" data-action="open-log" data-id="${esc(action.id)}">＋ Log</button><a class="samt-button ghost" href="#/actions/${encodeURIComponent(action.id)}">Open</a><a class="samt-button ghost" href="#/actions/${encodeURIComponent(action.id)}/edit">Edit</a>${action.status === "active" ? `<button class="samt-button ghost danger" data-action="archive-action" data-id="${esc(action.id)}">Archive</button>` : ""}</div></article>`;
}

export function renderActionsView({ state = {}, query = {} } = {}) {
  const direction = query.direction || "all"; const search = String(query.search || "").toLocaleLowerCase(); const actions = (state.actions || []).filter((action) => (direction === "all" || action.direction === direction) && (!search || `${action.name} ${action.description}`.toLocaleLowerCase().includes(search)));
  const categories = state.categories || []; return `<section class="samt-page" aria-labelledby="actions-title"><header class="samt-page-head"><div><p class="samt-eyebrow">Definitions · factual logging</p><h1 id="actions-title">Actions</h1><p class="samt-muted">An Action describes what happened. Scheduling belongs to its relationships.</p></div><button class="samt-button primary" data-action="new-action">＋ New Action</button></header><div class="samt-toolbar"><input class="samt-input" data-filter="action-search" value="${esc(query.search || "")}" placeholder="Search Actions" aria-label="Search Actions"><select class="samt-input" data-filter="action-direction"><option value="all" ${direction === "all" ? "selected" : ""}>All directions</option><option value="do" ${direction === "do" ? "selected" : ""}>Do</option><option value="avoid" ${direction === "avoid" ? "selected" : ""}>Avoid</option></select><span class="samt-muted">${actions.length} shown · ${categories.length} categories</span></div><div class="samt-card-grid">${actions.length ? actions.map((action) => actionCard(state, action)).join("") : `<article class="samt-card"><p class="samt-empty">No Actions yet. Create one to begin.</p></article>`}</div></section>`;
}

export function renderActionDetailView({ state = {}, action = null } = {}) {
  if (!action) return `<section class="samt-page"><div class="samt-empty-state"><h1>Action not found</h1><a class="samt-button" href="#/actions">Back to Actions</a></div></section>`;
  const logs = actionLogsFor(state, action.id); return `<section class="samt-page" aria-labelledby="action-detail-title"><header class="samt-page-head"><div><a class="samt-back" href="#/actions">← Actions</a><h1 id="action-detail-title">${esc(action.name)}</h1><p class="samt-muted">${esc(action.description || "No description")}</p></div><div class="samt-card-actions"><button class="samt-button primary" data-action="open-log" data-id="${esc(action.id)}">＋ Log</button><a class="samt-button ghost" href="#/actions/${encodeURIComponent(action.id)}/edit">Edit</a></div></header><div class="samt-detail-grid"><article class="samt-card"><h2>Definition</h2><dl class="samt-definition-list"><div><dt>Direction</dt><dd>${esc(titleCase(action.direction))}</dd></div><div><dt>Completion</dt><dd>${esc(titleCase(action.completion?.method))} · ${action.completion?.method === "quantity" ? esc(action.completion.target) : `${esc(action.completion?.minimumMinutes ?? 0)} minutes`}</dd></div><div><dt>Status</dt><dd>${esc(statusLabel(action.status))}</dd></div><div><dt>Tags</dt><dd>${(action.tagIds || []).map((id) => esc(state.tags?.find((tag) => tag.id === id)?.name || id)).join(", ") || "—"}</dd></div></dl></article><article class="samt-card"><div class="samt-card-head"><h2>Results</h2><button class="samt-button small" data-action="add-result" data-id="${esc(action.id)}">＋ Add Result</button></div><p class="samt-muted">${(action.resultFields || []).length} / 10 fields. Values are stored on each Action Log.</p><div class="samt-result-list">${(action.resultFields || []).length ? action.resultFields.map((field) => resultSummary(field, action.id)).join("") : `<p class="samt-empty">No Result Fields configured.</p>`}</div></article></div><article class="samt-card"><div class="samt-card-head"><h2>Factual History</h2><span class="samt-count">${logs.length}</span></div><div class="samt-list">${logs.length ? logs.map((log) => `<div class="samt-list-row"><div><strong>${esc(fmtDateTime(log.eventAt))}</strong><small>${esc(log.note || "Action log")}</small></div><div class="samt-metric"><b>${fmtMinutes(log.durationMinutes)}</b>${log.quantity != null ? `<span>${esc(String(log.quantity))} qty</span>` : ""}</div></div>`).join("") : `<p class="samt-empty">No logs yet.</p>`}</div></article></section>`;
}

function avoidFields(action) {
  const config = action?.avoid || {};
  const anchors = (config.anchors || []).map((anchor) => Number(anchor.actual) + "=" + Number(anchor.score)).join("\n");
  return '<fieldset class="samt-fieldset"><legend>Avoid configuration</legend><div class="samt-form-grid"><label>Mode<select class="samt-input" name="avoidMode"><option value="binary_limit"' + (config.mode === "binary_limit" || !config.mode ? " selected" : "") + '>Binary limit</option><option value="scored_range"' + (config.mode === "scored_range" ? " selected" : "") + '>Scored range</option><option value="violation_multiplier"' + (config.mode === "violation_multiplier" ? " selected" : "") + '>Violation multiplier</option></select></label><label>Metric<select class="samt-input" name="avoidMetric"><option value="duration"' + (config.metric !== "count" ? " selected" : "") + '>Duration minutes</option><option value="count"' + (config.metric === "count" ? " selected" : "") + '>Log count</option></select></label><label>Period<select class="samt-input" name="avoidPeriod"><option value="session"' + (config.period === "session" ? " selected" : "") + '>Session</option><option value="day"' + (config.period === "day" || !config.period ? " selected" : "") + '>Day</option><option value="week"' + (config.period === "week" ? " selected" : "") + '>Week</option><option value="month"' + (config.period === "month" ? " selected" : "") + '>Month</option><option value="all_time"' + (config.period === "all_time" ? " selected" : "") + '>All time</option></select></label><label>Period style<select class="samt-input" name="avoidPeriodStyle"><option value="calendar"' + (config.periodStyle !== "rolling" ? " selected" : "") + '>Calendar</option><option value="rolling"' + (config.periodStyle === "rolling" ? " selected" : "") + '>Rolling</option></select></label><label>Allowed limit / violations<input class="samt-input" name="avoidAllowed" type="number" min="0" step="any" value="' + esc(String(config.allowed ?? 0)) + '"></label><label>Penalty percent<input class="samt-input" name="avoidPenaltyPercent" type="number" min="0" step="any" value="' + esc(String(config.penaltyPercent ?? 100)) + '"></label></div><label>Scored anchors (actual=score, one per line)<textarea class="samt-input" name="avoidAnchors" rows="3" placeholder="0=100&#10;10=0">' + esc(anchors) + '</textarea></label><small class="samt-muted">No logs means no inferred usage. Avoid status remains separate from positive productivity.</small></fieldset>';
}

export function renderActionEditView({ state = {}, action = null } = {}) {
  if (!action) return '<section class="samt-page"><div class="samt-empty-state"><h1>Action not found</h1></div></section>';
  const tagIds = new Set(action.tagIds || []);
  const tags = (state.tags || []).filter((tag) => tag.status !== "archived" && ["action", "both"].includes(tag.scope));
  const completionValue = action.completion?.method === "quantity" ? action.completion.target : action.completion?.minimumMinutes ?? 0;
  return '<section class="samt-page" aria-labelledby="action-edit-title"><header class="samt-page-head"><div><a class="samt-back" href="#/actions/' + encodeURIComponent(action.id) + '">← ' + esc(action.name) + '</a><h1 id="action-edit-title">Edit Action</h1><p class="samt-muted">Definition changes apply to future logs; old logs retain snapshots. Stable Action ID: ' + esc(action.id) + '</p></div></header><form class="samt-card samt-form" data-form="edit-action" data-id="' + esc(action.id) + '"><div class="samt-form-grid"><label>Name<input class="samt-input" name="name" value="' + esc(action.name) + '" required></label><label>Direction<select class="samt-input" name="direction"><option value="do"' + (action.direction === "do" ? " selected" : "") + '>Do</option><option value="avoid"' + (action.direction === "avoid" ? " selected" : "") + '>Avoid</option></select></label><label>Completion method<select class="samt-input" name="completionMethod"><option value="time"' + (action.completion?.method === "time" ? " selected" : "") + '>Time</option><option value="quantity"' + (action.completion?.method === "quantity" ? " selected" : "") + '>Quantity</option></select></label><label>Minimum / target<input class="samt-input" type="number" min="0" step="any" name="completionValue" value="' + esc(String(completionValue)) + '"></label></div><label>Description<textarea class="samt-input" name="description" rows="3">' + esc(action.description || "") + '</textarea><fieldset><legend>Action Tags</legend><div class="samt-check-grid">' + (tags.map((tag) => '<label class="samt-check"><input type="checkbox" name="tagId" value="' + esc(tag.id) + '"' + (tagIds.has(tag.id) ? " checked" : "") + '> ' + esc(tag.name) + '</label>').join("") || '<span class="samt-muted">Create Action Tags in Settings.</span>') + '</div></fieldset>' + avoidFields(action) + '<p class="samt-form-error" data-form-error role="alert"></p><div class="samt-form-actions"><button class="samt-button primary" type="submit">Save Action</button><a class="samt-button ghost" href="#/actions/' + encodeURIComponent(action.id) + '">Cancel</a></div></form></section>';
}
