import { esc, fmtDateTime, fmtMinutes, statusLabel, typeLabel } from "./helpers.js";

function selectOptions(items, selected, label = (item) => item.name, value = (item) => item.id) {
  return items.map((item) => '<option value="' + esc(value(item)) + '"' + (String(selected || "") === String(value(item)) ? " selected" : "") + '>' + esc(label(item)) + '</option>').join("");
}

function resultFields(state) {
  return (state.actions || []).flatMap((action) => (action.resultFields || []).map((field) => ({ ...field, actionName: action.name })));
}

function resultValue(result, key) {
  return result?.[key] == null ? "—" : String(result[key]);
}

export function renderAnalysisView({ model = {}, state = {}, filters = {} } = {}) {
  const fields = resultFields(state);
  const resultTags = (state.tags || []).filter((tag) => ["result", "both"].includes(tag.scope));
  const blocks = state.blocks || [];
  const blockTypes = [...new Set(blocks.map((block) => block.type))];
  const targetBlocks = blocks.filter((block) => block.type === "target");
  const target = model.target;
  const periods = model.targetPeriods || [];
  const attribution = filters.attribution || (filters.blockId ? (filters.inclusive === "false" ? "direct" : "inclusive") : "global");
  const targetProgress = target ? state.__targetProgress?.[target.id] : null;
  const result = model.result;
  const resultMarkup = result ? '<article class="samt-card"><div class="samt-card-head"><h2>Result analysis</h2><span class="samt-badge">' + esc(result.type || "result") + '</span></div>' + (result.error ? '<p class="samt-form-error">' + esc(result.error) + '</p>' : '<dl class="samt-definition-list"><div><dt>Count</dt><dd>' + resultValue(result, "count") + '</dd></div><div><dt>Latest / value</dt><dd>' + esc(resultValue(result, "latest") !== "—" ? resultValue(result, "latest") : resultValue(result, "value")) + (result.unitSymbol ? " " + esc(result.unitSymbol) : "") + '</dd></div><div><dt>Average</dt><dd>' + esc(resultValue(result, "average") !== "—" ? resultValue(result, "average") : resultValue(result, "numericAverage")) + (result.unitSymbol ? " " + esc(result.unitSymbol) : "") + '</dd></div><div><dt>Range</dt><dd>' + esc(resultValue(result, "min")) + ' → ' + esc(resultValue(result, "max")) + (result.unitSymbol ? " " + esc(result.unitSymbol) : "") + '</dd></div></dl>') + '</article>' : "";
  const periodMarkup = target ? '<article class="samt-card"><div class="samt-card-head"><h2>Target periods</h2><span class="samt-count">' + periods.length + '</span></div>' + (targetProgress ? '<p class="samt-muted">Current: ' + esc(String(targetProgress.actual ?? "—")) + ' / ' + esc(String(targetProgress.targetValue ?? target.config?.targetValue ?? "—")) + ' · ' + esc(statusLabel(targetProgress.status || "not_started")) + '</p>' : "") + '<div class="samt-table-wrap"><table class="samt-table"><thead><tr><th>Bounds</th><th>Status</th><th>Target snapshot</th><th>Actual</th></tr></thead><tbody>' + (periods.map((period) => '<tr><td>' + esc(fmtDateTime(period.start)) + ' → ' + esc(fmtDateTime(period.end)) + '</td><td>' + esc(statusLabel(period.status || period.evaluation?.status || "closed")) + '</td><td>' + esc(String(period.snapshot?.targetValue ?? target.config?.targetValue ?? "—")) + '</td><td>' + esc(String(period.evaluation?.actual ?? period.evaluation?.value ?? "—")) + '</td></tr>').join("") || '<tr><td colspan="4" class="samt-empty">No closed Target periods recorded.</td></tr>') + '</tbody></table></div></article>' : "";
  return '<section class="samt-page" aria-labelledby="analysis-title"><header class="samt-page-head"><div><p class="samt-eyebrow">Derived read model · factual records</p><h1 id="analysis-title">Analysis</h1><p class="samt-muted">Use Direct, Inclusive Unique, or Descendant attribution explicitly. Measurement analysis is normalised to a compatible Unit and never combines incompatible dimensions.</p></div></header>' +
    '<form class="samt-card samt-toolbar" data-form="analysis-filter"><div class="samt-form-grid">' +
      '<label>View<select class="samt-input" name="view"><option value="all"' + (!filters.view || filters.view === "all" ? " selected" : "") + '>All</option><option value="actions"' + (filters.view === "actions" ? " selected" : "") + '>Positive Actions</option><option value="avoid"' + (filters.view === "avoid" ? " selected" : "") + '>Avoid</option><option value="results"' + (filters.view === "results" ? " selected" : "") + '>Results</option><option value="targets"' + (filters.view === "targets" ? " selected" : "") + '>Targets</option><option value="blocks"' + (filters.view === "blocks" ? " selected" : "") + '>Blocks</option></select></label>' +
      '<label>Block<select class="samt-input" name="blockId"><option value="">All Blocks</option>' + selectOptions(blocks, filters.blockId, (block) => block.name + " · " + typeLabel(block.type)) + '</select></label>' +
      '<label>Block Type<select class="samt-input" name="blockType"><option value="">All types</option>' + blockTypes.map((type) => '<option value="' + esc(type) + '"' + (filters.blockType === type ? " selected" : "") + '>' + esc(typeLabel(type)) + '</option>').join("") + '</select></label>' +
      '<label>Attribution<select class="samt-input" name="attribution"><option value="global"' + (attribution === "global" ? " selected" : "") + '>Global Unique</option><option value="direct"' + (attribution === "direct" ? " selected" : "") + '>Direct Only</option><option value="inclusive"' + (attribution === "inclusive" ? " selected" : "") + '>Inclusive Unique</option><option value="descendant"' + (attribution === "descendant" ? " selected" : "") + '>Descendant Only</option></select></label>' +
      '<label>Action<select class="samt-input" name="actionId"><option value="">All Actions</option>' + selectOptions(state.actions || [], filters.actionId) + '</select></label>' +
      '<label>Category<select class="samt-input" name="categoryId"><option value="">All Categories</option>' + selectOptions(state.categories || [], filters.categoryId) + '</select></label>' +
      '<label>Tag<select class="samt-input" name="tagId"><option value="">All Tags</option>' + selectOptions(state.tags || [], filters.tagId) + '</select></label>' +
      '<label>Run<select class="samt-input" name="runId"><option value="">All Runs</option>' + selectOptions(state.runs || [], filters.runId, (run) => (run.label || run.id) + " · " + run.status) + '</select></label>' +
      '<label>Result Tag<select class="samt-input" name="resultTagId"><option value="">All Result Tags</option>' + selectOptions(resultTags, filters.resultTagId) + '</select></label>' +
      '<label>Result Field<select class="samt-input" name="resultFieldId"><option value="">All Result Fields</option>' + selectOptions(fields, filters.resultFieldId, (field) => field.label + " · " + field.actionName) + '</select></label>' +
      '<label>Target<select class="samt-input" name="targetId"><option value="">All Targets</option>' + selectOptions(targetBlocks, filters.targetId) + '</select></label>' +
      '<label>Target Period<select class="samt-input" name="targetPeriodId"><option value="">All periods</option>' + selectOptions((state.periods || []).filter((period) => !filters.targetId || period.ownerId === filters.targetId), filters.targetPeriodId, (period) => fmtDateTime(period.start) + " → " + fmtDateTime(period.end)) + '</select></label>' +
      '<label>From<input class="samt-input" name="from" type="date" value="' + esc(filters.from || "") + '"></label><label>To<input class="samt-input" name="to" type="date" value="' + esc(filters.to || "") + '"></label>' +
    '</div><div class="samt-form-actions"><button class="samt-button primary" type="submit">Apply Filters</button><a class="samt-button ghost" href="#/analysis">Reset</a></div></form>' +
    '<div class="samt-stat-grid"><article class="samt-card"><span class="samt-eyebrow">Scope</span><strong class="samt-stat-value">' + esc(model.scope || "GLOBAL_UNIQUE") + '</strong><small>' + (model.logCount || 0) + ' factual log' + (model.logCount === 1 ? "" : "s") + '</small></article><article class="samt-card"><span class="samt-eyebrow">Unique time</span><strong class="samt-stat-value">' + fmtMinutes(model.totalMinutes || 0) + '</strong><small>One real-world event remains one log</small></article><article class="samt-card"><span class="samt-eyebrow">Unique quantity</span><strong class="samt-stat-value">' + esc(String((model.logs || []).reduce((sum, log) => sum + Number(log.quantity || 0), 0))) + '</strong><small>Factual quantity across logs</small></article></div>' +
    resultMarkup + periodMarkup +
    '<article class="samt-card"><div class="samt-card-head"><h2>Target library</h2><span class="samt-count">' + targetBlocks.length + '</span></div><div class="samt-list">' + (targetBlocks.map((item) => '<div class="samt-list-row"><div><a href="#/blocks/' + encodeURIComponent(item.id) + '"><strong>' + esc(item.name) + '</strong></a><small>' + esc(item.config?.period || "all_time") + ' · ' + esc(statusLabel(state.__targetProgress?.[item.id]?.status || "not_started")) + '</small></div><div class="samt-metric"><b>' + esc(String(state.__targetProgress?.[item.id]?.actual ?? "—")) + '</b><span>/ ' + esc(String(state.__targetProgress?.[item.id]?.targetValue ?? item.config?.targetValue ?? "—")) + '</span></div></div>').join("") || '<p class="samt-empty">No Target Blocks yet.</p>') + '</div></article>' +
    '<article class="samt-card"><div class="samt-card-head"><h2>Logs in scope</h2><span class="samt-count">' + (model.logs || []).length + '</span></div><div class="samt-list">' + ((model.logs || []).slice(0, 50).map((log) => '<div class="samt-list-row"><div><strong>' + esc(log.actionSnapshot?.name || log.actionId) + '</strong><small>' + esc(fmtDateTime(log.eventAt)) + ' · ' + esc(log.contextRefs?.map((reference) => reference.blockId || reference.runId || reference.occurrenceId).filter(Boolean).join(", ") || "No context") + '</small></div><div class="samt-metric"><b>' + fmtMinutes(log.durationMinutes) + '</b>' + (log.quantity != null ? '<span>' + esc(String(log.quantity)) + ' qty</span>' : "") + '</div></div>').join("") || '<p class="samt-empty">No logs match these filters.</p>') + '</div></article></section>';
}
