import { BLOCK_LABELS, blockById, esc, relationshipLabel, statusLabel, titleCase, typeLabel } from "./helpers.js";

function blockCard(block) {
  const relationships = block.relationships || []; return `<article class="samt-card samt-entity-card"><div class="samt-card-head"><div><a class="samt-entity-link" href="#/blocks/${encodeURIComponent(block.id)}"><h2>${esc(block.name)}</h2></a><span class="samt-badge">${esc(typeLabel(block.type))}</span></div><span class="samt-status">${esc(statusLabel(block.definitionStatus))}</span></div><p class="samt-muted">${esc(block.description || "No description")}</p><div class="samt-stat-line"><span>${relationships.length} relationship${relationships.length === 1 ? "" : "s"}</span><span>${esc(block.config?.period || block.config?.generationMode || "Reusable definition")}</span></div><div class="samt-card-actions"><a class="samt-button" href="#/blocks/${encodeURIComponent(block.id)}">Open</a><a class="samt-button ghost" href="#/blocks/${encodeURIComponent(block.id)}/edit">Edit</a>${block.definitionStatus === "ACTIVE" ? `<button class="samt-button ghost" data-action="pause-block" data-id="${esc(block.id)}">Pause</button>` : block.definitionStatus === "PAUSED" ? `<button class="samt-button ghost" data-action="activate-block" data-id="${esc(block.id)}">Activate</button>` : ""}</div></article>`;
}

export function renderBlocksView({ state = {}, filterType = "all" } = {}) {
  const blocks = (state.blocks || []).filter((block) => filterType === "all" || block.type === filterType); return `<section class="samt-page" aria-labelledby="blocks-title"><header class="samt-page-head"><div><p class="samt-eyebrow">Definitions · relationships · runtime</p><h1 id="blocks-title">Blocks</h1><p class="samt-muted">Open uses a definition. Edit changes the reusable definition.</p></div><button class="samt-button primary" data-action="new-block">＋ New Block</button></header><div class="samt-chip-row">${[["all", "All"], ...Object.entries(BLOCK_LABELS)].map(([value, label]) => `<a class="samt-chip ${filterType === value ? "selected" : ""}" href="#/blocks?type=${encodeURIComponent(value)}">${esc(label)}</a>`).join("")}</div><div class="samt-card-grid">${blocks.length ? blocks.map(blockCard).join("") : `<article class="samt-card"><p class="samt-empty">No ${filterType === "all" ? "Blocks" : esc(typeLabel(filterType)) + " Blocks"} yet.</p></article>`}</div></section>`;
}

function childRow(state, block, relationship) {
  const target = relationship.kind === "action" ? state.actions?.find((action) => action.id === relationship.refId) : blockById(state, relationship.refId); const href = relationship.kind === "action" ? `#/actions/${encodeURIComponent(relationship.refId)}` : `#/blocks/${encodeURIComponent(relationship.refId)}`; return `<div class="samt-list-row"><div><a href="${href}"><strong>${esc(relationship.label || target?.name || "Missing reference")}</strong></a><small>${esc(relationship.kind)} · position ${Number(relationship.position || 0) + 1}${relationship.config?.required ? " · Required" : ""}${relationship.config?.schedule?.mode ? ` · ${esc(relationship.config.schedule.mode)}` : ""}</small></div><div class="samt-row-actions">${relationship.kind === "action" && target ? `<button class="samt-button small" data-action="open-log" data-id="${esc(target.id)}" data-block-id="${esc(block.id)}">＋ Log</button>` : ""}<button class="samt-button ghost small" data-action="remove-relationship" data-block-id="${esc(block.id)}" data-id="${esc(relationship.id)}">Remove</button></div></div>`;
}

function targetSummary(state, block) {
  if (block.type !== "target") return ""; const progress = state.__targetProgress?.[block.id]; return `<article class="samt-card"><div class="samt-card-head"><h2>Target</h2><span class="samt-badge">${esc(titleCase(block.config?.mode || "accumulation"))}</span></div><p class="samt-target-large">${esc(String(progress?.actual ?? 0))} <small>/ ${esc(String(progress?.targetValue ?? block.config?.targetValue ?? 0))}</small></p><div class="samt-progress"><span style="width:${Math.min(100, Number(progress?.percentage) || 0)}%"></span></div><p class="samt-muted">${esc(statusLabel(progress?.status || "not_started"))} · ${esc(String(progress?.percentage ?? 0))}% · scope ${esc(block.config?.contributionScope || "direct")}</p></article>`;
}

export function renderBlockDetailView({ state = {}, block = null } = {}) {
  if (!block) return `<section class="samt-page"><div class="samt-empty-state"><h1>Block not found</h1><a class="samt-button" href="#/blocks">Back to Blocks</a></div></section>`;
  const runs = (state.runs || []).filter((run) => run.blockId === block.id); const children = (block.relationships || []).slice().sort((a, b) => a.position - b.position); return `<section class="samt-page" aria-labelledby="block-detail-title"><header class="samt-page-head"><div><a class="samt-back" href="#/blocks">← Blocks</a><p class="samt-eyebrow">${esc(typeLabel(block.type))}</p><h1 id="block-detail-title">${esc(block.name)}</h1><p class="samt-muted">${esc(block.description || "No description")}</p></div><div class="samt-card-actions">${["routine", "workflow", "project", "cycle"].includes(block.type) ? `<button class="samt-button primary" data-action="start-run" data-id="${esc(block.id)}">Run now</button>` : ""}<a class="samt-button ghost" href="#/blocks/${encodeURIComponent(block.id)}/edit">Edit definition</a></div></header><div class="samt-detail-grid"><article class="samt-card"><div class="samt-card-head"><h2>Definition</h2><span class="samt-status">${esc(statusLabel(block.definitionStatus))}</span></div><dl class="samt-definition-list"><div><dt>Type</dt><dd>${esc(typeLabel(block.type))}</dd></div><div><dt>Relationships</dt><dd>${children.length}</dd></div><div><dt>Runtime</dt><dd>${runs.length ? `${runs.filter((run) => run.status === "IN_PROGRESS").length} running · ${runs.length} total` : "No Runs"}</dd></div></dl></article>${targetSummary(state, block)}</div><article class="samt-card"><div class="samt-card-head"><div><h2>Relationships</h2><p class="samt-muted">Context lives here; Actions and Blocks remain reusable definitions.</p></div><button class="samt-button small" data-action="add-relationship" data-id="${esc(block.id)}">＋ Add</button></div><div class="samt-list">${children.length ? children.map((relationship) => childRow(state, block, relationship)).join("") : `<p class="samt-empty">No children yet.</p>`}</div></article>${runs.length ? `<article class="samt-card"><div class="samt-card-head"><h2>Runs</h2><span class="samt-count">${runs.length}</span></div><div class="samt-list">${runs.slice().reverse().map((run) => `<div class="samt-list-row"><div><strong>${esc(run.label || "Untitled Run")}</strong><small>${esc(statusLabel(run.status))} · ${esc(run.startedAt || run.createdAt || "")}</small></div><div class="samt-row-actions">${run.status === "IN_PROGRESS" ? `<button class="samt-button small" data-action="finish-run" data-id="${esc(run.id)}">Finish</button><button class="samt-button ghost small" data-action="pause-run" data-id="${esc(run.id)}">Pause</button>` : run.status === "PAUSED" ? `<button class="samt-button small" data-action="resume-run" data-id="${esc(run.id)}">Resume</button>` : ""}</div></div>`).join("")}</div></article>` : ""}</section>`;
}

function resultFieldOptions(state, selected = "") {
  return (state.actions || []).flatMap((action) => (action.resultFields || []).map((field) => `<option value="${esc(field.id)}" ${field.id === selected ? "selected" : ""}>${esc(action.name)} · ${esc(field.label)}</option>`)).join("");
}

function configFields(block, state = {}) {
  const config = block?.config || {};
  if (block?.type === "target") return `<div class="samt-form-grid"><label>Mode<select class="samt-input" name="config.mode"><option value="accumulation" ${config.mode === "accumulation" ? "selected" : ""}>Accumulation</option><option value="outcome" ${config.mode === "outcome" ? "selected" : ""}>Outcome</option></select></label><label>Metric<select class="samt-input" name="config.metric"><option value="time" ${config.metric === "time" ? "selected" : ""}>Time</option><option value="quantity" ${config.metric === "quantity" ? "selected" : ""}>Quantity</option><option value="completion_count" ${config.metric === "completion_count" ? "selected" : ""}>Completion count</option></select></label><label>Target value<input class="samt-input" name="config.targetValue" type="text" value="${esc(String(config.targetValue ?? 0))}"></label><label>Comparison<select class="samt-input" name="config.comparison">${[">=", ">", "=", "<=", "<"].map((item) => `<option value="${item}" ${config.comparison === item ? "selected" : ""}>${item}</option>`).join("")}</select></label><label>Period<select class="samt-input" name="config.period">${["session", "day", "week", "month", "custom", "all_time"].map((item) => `<option value="${item}" ${config.period === item ? "selected" : ""}>${titleCase(item)}</option>`).join("")}</select></label><label>Period style<select class="samt-input" name="config.periodStyle"><option value="calendar" ${config.periodStyle !== "rolling" ? "selected" : ""}>Calendar</option><option value="rolling" ${config.periodStyle === "rolling" ? "selected" : ""}>Rolling</option></select></label><label>Contribution<select class="samt-input" name="config.contributionScope"><option value="direct" ${config.contributionScope !== "inclusive" ? "selected" : ""}>Direct only</option><option value="inclusive" ${config.contributionScope === "inclusive" ? "selected" : ""}>Inclusive unique descendants</option></select></label><label>Source Actions<select class="samt-input" name="sourceActionId" multiple size="4">${(state.actions || []).filter((action) => action.status !== "archived").map((action) => `<option value="${esc(action.id)}" ${(config.sourceActionIds || []).includes(action.id) ? "selected" : ""}>${esc(action.name)}</option>`).join("")}</select></label><label>Outcome Result Field<select class="samt-input" name="config.sourceResultFieldId"><option value="">Choose for outcome Targets</option>${resultFieldOptions(state, config.sourceResultFieldId)}</select></label><label>Outcome aggregation<select class="samt-input" name="config.aggregation">${["latest", "highest", "lowest", "average"].map((item) => `<option value="${item}" ${config.aggregation === item ? "selected" : ""}>${titleCase(item)}</option>`).join("")}</select></label><label>Unit ID (for measurements)<input class="samt-input" name="config.unitId" value="${esc(String(config.unitId || ""))}" placeholder="Optional compatible Unit ID"></label></div>`;
  if (block?.type === "cycle") return `<div class="samt-form-grid"><label>Generation<select class="samt-input" name="config.generationMode"><option value="simple_ordered" ${config.generationMode === "simple_ordered" ? "selected" : ""}>Simple ordered</option><option value="exact_frequency" ${config.generationMode === "exact_frequency" ? "selected" : ""}>Exact frequency</option><option value="weighted_limited" ${config.generationMode === "weighted_limited" ? "selected" : ""}>Weighted limited</option></select></label><label>Eligibility<select class="samt-input" name="config.eligibility"><option value="strict_order" ${config.eligibility !== "next_eligible" ? "selected" : ""}>Strict order</option><option value="next_eligible" ${config.eligibility === "next_eligible" ? "selected" : ""}>Next eligible</option></select></label><label>Small Cycle slots<input class="samt-input" name="config.smallCycleSize" type="number" min="1" step="1" value="${esc(String(config.smallCycleSize ?? ""))}"></label><label>Missed item policy<select class="samt-input" name="config.missedItemPolicy"><option value="keep_position" ${config.missedItemPolicy !== "advance_to_next" ? "selected" : ""}>Keep position</option><option value="advance_to_next" ${config.missedItemPolicy === "advance_to_next" ? "selected" : ""}>Advance to next</option><option value="restart_small_cycle" ${config.missedItemPolicy === "restart_small_cycle" ? "selected" : ""}>Restart Small Cycle</option><option value="restart_big_cycle" ${config.missedItemPolicy === "restart_big_cycle" ? "selected" : ""}>Restart Big Cycle</option></select></label><label>Period end<select class="samt-input" name="config.periodEnd"><option value="never" ${config.periodEnd !== "auto" ? "selected" : ""}>Never</option><option value="auto" ${config.periodEnd === "auto" ? "selected" : ""}>Auto close</option></select></label><label>Position policy<select class="samt-input" name="config.positionPolicy"><option value="continue" ${config.positionPolicy !== "restart" ? "selected" : ""}>Continue</option><option value="restart" ${config.positionPolicy === "restart" ? "selected" : ""}>Restart from beginning</option></select></label></div>`;
  if (block?.type === "routine") return `<div class="samt-form-grid"><label>Completion mode<select class="samt-input" name="config.completionMode"><option value="required_only" ${config.completionMode === "required_only" ? "selected" : ""}>Required only</option><option value="count" ${config.completionMode === "count" ? "selected" : ""}>Count</option><option value="percentage" ${config.completionMode === "percentage" ? "selected" : ""}>Percentage</option><option value="manual" ${config.completionMode === "manual" ? "selected" : ""}>Manual</option></select></label><label>Minimum count<input class="samt-input" name="config.minimumCount" type="number" min="0" step="1" value="${esc(String(config.minimumCount ?? 0))}"></label><label>Minimum percentage<input class="samt-input" name="config.minimumPercentage" type="number" min="0" max="100" step="1" value="${esc(String(config.minimumPercentage ?? 100))}"></label><label>Finish behaviour<select class="samt-input" name="config.finishBehaviour"><option value="auto" ${config.finishBehaviour !== "ready" ? "selected" : ""}>Auto finish</option><option value="ready" ${config.finishBehaviour === "ready" ? "selected" : ""}>Ready to finish</option></select></label></div>`;
  if (block?.type === "workflow") return `<div class="samt-form-grid"><label>Finish behaviour<select class="samt-input" name="config.finishBehaviour"><option value="auto" ${config.finishBehaviour !== "confirm" ? "selected" : ""}>Auto finish</option><option value="confirm" ${config.finishBehaviour === "confirm" ? "selected" : ""}>Require confirmation</option></select></label><label>Progression<select class="samt-input" name="config.progression"><option value="ordered" ${config.progression !== "stages" ? "selected" : ""}>Ordered steps</option><option value="stages" ${config.progression === "stages" ? "selected" : ""}>Stages (future-ready)</option></select></label></div>`;
  if (block?.type === "project") return `<div class="samt-form-grid"><label>Condition combination<select class="samt-input" name="config.combination"><option value="all" ${config.combination !== "any" ? "selected" : ""}>All conditions</option><option value="any" ${config.combination === "any" ? "selected" : ""}>Any condition</option></select></label><label>Finish behaviour<select class="samt-input" name="config.finishBehaviour"><option value="ready" ${config.finishBehaviour !== "auto" ? "selected" : ""}>Ready to finish</option><option value="auto" ${config.finishBehaviour === "auto" ? "selected" : ""}>Auto finish</option></select></label><label>Deadline<input class="samt-input" name="config.deadline" type="date" value="${esc(String(config.deadline || ""))}"></label><label>Deadline policy<select class="samt-input" name="config.deadlinePolicy"><option value="continue_overdue" ${config.deadlinePolicy !== "hard_expiry" ? "selected" : ""}>Continue overdue</option><option value="hard_expiry" ${config.deadlinePolicy === "hard_expiry" ? "selected" : ""}>Expire unfinished</option></select></label></div>`;
  if (block?.type === "action_list") return `<div class="samt-form-grid"><label>Default unfinished policy<select class="samt-input" name="config.occurrencePolicy"><option value="expire" ${config.occurrencePolicy !== "carry_forward" && config.occurrencePolicy !== "stay_overdue" ? "selected" : ""}>Expire</option><option value="carry_forward" ${config.occurrencePolicy === "carry_forward" ? "selected" : ""}>Carry forward</option><option value="stay_overdue" ${config.occurrencePolicy === "stay_overdue" ? "selected" : ""}>Stay overdue</option></select></label><label>List behaviour<select class="samt-input" name="config.listMode"><option value="open_ended" ${config.listMode !== "configured_occurrences" ? "selected" : ""}>Open-ended pool</option><option value="configured_occurrences" ${config.listMode === "configured_occurrences" ? "selected" : ""}>Configured occurrences</option></select></label></div>`;
  return `<p class="samt-muted">This type has no extra configuration. Add relationships to define its structure.</p>`;
}

export function renderBlockEditView({ state = {}, block = null } = {}) {
  if (!block) return `<section class="samt-page"><div class="samt-empty-state"><h1>Block not found</h1></div></section>`;
  return `<section class="samt-page" aria-labelledby="block-edit-title"><header class="samt-page-head"><div><a class="samt-back" href="#/blocks/${encodeURIComponent(block.id)}">← ${esc(block.name)}</a><h1 id="block-edit-title">Edit ${esc(typeLabel(block.type))}</h1><p class="samt-muted">Permanent definition. Active Runs keep their start snapshot.</p></div></header><form class="samt-card samt-form" data-form="edit-block" data-id="${esc(block.id)}"><div class="samt-form-grid"><label>Name<input class="samt-input" name="name" value="${esc(block.name)}" required></label><label>Definition status<select class="samt-input" name="definitionStatus">${["LIBRARY", "ACTIVE", "PAUSED", "ARCHIVED"].map((status) => `<option value="${status}" ${block.definitionStatus === status ? "selected" : ""}>${statusLabel(status)}</option>`).join("")}</select></label></div><label>Description<textarea class="samt-input" name="description" rows="3">${esc(block.description || "")}</textarea><fieldset><legend>Type configuration</legend>${configFields(block, state)}</fieldset><div class="samt-form-actions"><button class="samt-button primary" type="submit">Save definition</button><a class="samt-button ghost" href="#/blocks/${encodeURIComponent(block.id)}">Cancel</a></div></form></section>`;
}
