import { esc, statusLabel, titleCase } from "./helpers.js";

function taxonomySection(state) {
  const categories = state.categories || []; const tags = state.tags || []; return `<article class="samt-card"><div class="samt-card-head"><div><h2>Categories & Tags</h2><p class="samt-muted">One shallow taxonomy shared by Actions and Results.</p></div><button class="samt-button small" data-action="new-category">＋ Category</button></div><div class="samt-settings-list">${categories.map((category) => `<div class="samt-list-row"><div><strong>${esc(category.name)}</strong><small>${esc(category.scope)} · ${esc(statusLabel(category.status))} · ${tags.filter((tag) => tag.categoryId === category.id).length} tags</small></div><button class="samt-button ghost small" data-action="archive-category" data-id="${esc(category.id)}">Archive</button></div>`).join("") || `<p class="samt-empty">No Categories. Add one to classify Actions and Results.</p>`}</div><div class="samt-inline-actions"><button class="samt-button ghost small" data-action="new-tag">＋ Tag</button></div></article>`;
}
function unitSection(state) { return `<article class="samt-card"><div class="samt-card-head"><div><h2>Units</h2><p class="samt-muted">Built-in compatible families plus custom standalone units.</p></div><button class="samt-button small" data-action="new-unit">＋ Custom unit</button></div><div class="samt-table-wrap"><table class="samt-table"><thead><tr><th>Name</th><th>Symbol</th><th>Dimension</th><th>Status</th></tr></thead><tbody>${(state.units || []).map((unit) => `<tr><td>${esc(unit.name)}</td><td>${esc(unit.symbol)}</td><td>${esc(unit.dimension)}</td><td>${unit.builtIn ? "Built-in" : esc(statusLabel(unit.status))}</td></tr>`).join("")}</tbody></table></div></article>`; }
function dataSection(state) { return `<article class="samt-card"><div class="samt-card-head"><div><h2>Data</h2><p class="samt-muted">Import/export is optional. SAMT opens with an empty state without JSON.</p></div></div><div class="samt-card-actions"><button class="samt-button primary" data-action="export">Export full backup</button><label class="samt-button ghost file-button">Import backup<input type="file" accept="application/json,.json" data-file="import" hidden></label><button class="samt-button ghost" data-action="restore-import">Undo last import</button></div><dl class="samt-definition-list compact"><div><dt>Storage</dt><dd>${state.__storageAvailable === false ? "In memory (browser storage unavailable)" : "Browser storage available"}</dd></div><div><dt>Schema</dt><dd>${esc(state.schemaVersion || "3.0.0")}</dd></div><div><dt>Migration</dt><dd>${esc(state.meta?.migratedFrom || state.legacy?.sourceSchemaVersion || "Fresh V3 state")}</dd></div></dl></article>`; }

export function renderSettingsView({ state = {}, section = "general" } = {}) {
  const settings = state.settings || {}; const defaults = settings.defaults || {}; const capacity = settings.capacity || {}; return `<section class="samt-page" aria-labelledby="settings-title"><header class="samt-page-head"><div><p class="samt-eyebrow">Engine configuration</p><h1 id="settings-title">Settings</h1><p class="samt-muted">Appearance controls are intentionally minimal. These settings affect scheduling and defaults.</p></div></header><form class="samt-card samt-form" data-form="settings"><div class="samt-form-grid"><label>Timezone<select class="samt-input" name="timezone">${["Europe/London", "UTC", "America/New_York", "America/Los_Angeles", "Asia/Manila", "Asia/Riyadh"].map((zone) => `<option value="${zone}" ${settings.timezone === zone ? "selected" : ""}>${zone}</option>`).join("")}</select></label><label>Week starts on<select class="samt-input" name="weekStartsOn">${[[1,"Monday"],[0,"Sunday"],[6,"Saturday"]].map(([value,label]) => `<option value="${value}" ${Number(settings.weekStartsOn) === value ? "selected" : ""}>${label}</option>`).join("")}</select></label><label>Available capacity (hours)<input class="samt-input" name="availableHours" type="number" min="0" step="0.25" value="${esc(String((Number(capacity.availableMinutes || 0) / 60).toFixed(2)))}"></label><label>Capacity window (days)<input class="samt-input" name="periodDays" type="number" min="1" max="14" step="1" value="${esc(String(capacity.periodDays || 7))}"></label></div><fieldset><legend>Block defaults</legend><div class="samt-check-grid"><label class="samt-check"><input type="checkbox" name="targetAutoClose" ${defaults.targetAutoClose !== false ? "checked" : ""}> Target periods auto-close</label><label class="samt-check"><input type="checkbox" name="cycleAutoClose" ${defaults.cycleAutoClose !== false ? "checked" : ""}> Cycle periods auto-close</label><label class="samt-check"><input type="checkbox" name="routineExpire" ${defaults.routineExpire !== false ? "checked" : ""}> Expire unfinished Routines</label><label class="samt-check"><input type="checkbox" name="actionListExpire" ${defaults.actionListExpire !== false ? "checked" : ""}> Expire Action List occurrences</label></div></fieldset><button class="samt-button primary" type="submit">Save settings</button></form><div class="samt-section-grid">${taxonomySection(state)}${unitSection(state)}</div>${dataSection(state)}</section>`;
}
