import { ConflictError, NotFoundError, ValidationError } from "../shared/errors.js";
import { clone, normalizedKey } from "../shared/validation.js";
import { createAction, validateAction, versionResultFields } from "../domain/actions.js";
import { createCategory, createTag, validateTaxonomy } from "../domain/taxonomy.js";
import { createUnit } from "../domain/units.js";
import { createResultField, validateResultFields } from "../domain/results.js";
import { createActionLog } from "../domain/logs.js";
import { createBlock } from "../domain/blocks.js";
import { createRelationship, validateBlockGraph } from "../domain/relationships.js";
import { createOccurrence } from "../domain/occurrences.js";
import { createRun, startRun as startDomainRun, finishRun as finishDomainRun } from "../domain/runs.js";
import { appendHistory } from "../domain/history.js";
import { domainEvent, EVENT_TYPES } from "./events.js";
import { importPackage } from "../import-export/importer.js";

export function createCommands(repository, { clock = () => new Date(), idFactory = null } = {}) {
  const now = () => new Date(clock());
  function addHistory(event) { const state = repository.getState(); state.history = appendHistory(state.history || [], { ...event, timestamp: event.timestamp || now() }); }
  function emit(type, payload) { const state = repository.getState(); state.meta = state.meta || {}; state.meta.events = [...(state.meta.events || []), domainEvent(type, payload, now())].slice(-500); }
  function ensureUnique(collection, item, label) { if (collection.some((candidate) => candidate.id !== item.id && normalizedKey(candidate.name) === normalizedKey(item.name))) throw new ConflictError(`${label} name already exists.`); }
  return {
    createCategory(input) { return repository.transaction(() => { const state = repository.getState(); const category = createCategory({ ...input, id: input.id || idFactory?.("category"), now: now() }); ensureUnique(state.categories, category, "Category"); state.categories.push(category); validateTaxonomy(state); addHistory({ type: "definition", description: `Created Category: ${category.name}`, objectType: "category", objectId: category.id }); return clone(category); }); },
    createTag(input) { return repository.transaction(() => { const state = repository.getState(); const tag = createTag({ ...input, id: input.id || idFactory?.("tag"), now: now() }, state.categories); if (state.tags.some((candidate) => candidate.categoryId === tag.categoryId && normalizedKey(candidate.name) === normalizedKey(tag.name))) throw new ConflictError("Tag name already exists in that Category."); state.tags.push(tag); validateTaxonomy(state); addHistory({ type: "definition", description: `Created Tag: ${tag.name}`, objectType: "tag", objectId: tag.id }); return clone(tag); }); },
    createUnit(input) { return repository.transaction(() => { const state = repository.getState(); const unit = createUnit({ ...input, id: input.id || idFactory?.("unit"), now: now() }); if (state.units.some((candidate) => candidate.name.toLocaleLowerCase() === unit.name.toLocaleLowerCase() || candidate.symbol === unit.symbol)) throw new ConflictError("Unit name or symbol already exists."); state.units.push(unit); addHistory({ type: "definition", description: `Created Unit: ${unit.name}`, objectType: "unit", objectId: unit.id }); return clone(unit); }); },
    createAction(input) { return repository.transaction(() => { const state = repository.getState(); const action = createAction({ ...input, id: input.id || idFactory?.("action"), now: now() }, { units: state.units }); validateAction(action, { units: state.units }); ensureUnique(state.actions, action, "Action"); state.actions.push(action); addHistory({ type: "definition", description: `Created Action: ${action.name}`, objectType: "action", objectId: action.id }); emit(EVENT_TYPES.DEFINITION_CHANGED, { objectType: "action", objectId: action.id }); return clone(action); }); },
    updateAction(id, patch) { return repository.transaction(() => { const state = repository.getState(); const index = state.actions.findIndex((action) => action.id === id); if (index < 0) throw new NotFoundError(`Action not found: ${id}`); const before = state.actions[index]; const next = { ...before, ...clone(patch), id, resultFields: patch.resultFields ? versionResultFields(before.resultFields || [], patch.resultFields, now()) : before.resultFields, updatedAt: now().toISOString() }; ensureUnique(state.actions, next, "Action"); validateAction(next, { units: state.units }); state.actions[index] = next; addHistory({ type: "definition", description: `Updated Action: ${next.name}`, objectType: "action", objectId: id, snapshots: { before: clone(before), after: clone(next) } }); return clone(next); }); },
    addResultField(actionId, input) { return repository.transaction(() => { const state = repository.getState(); const index = state.actions.findIndex((action) => action.id === actionId); if (index < 0) throw new NotFoundError(`Action not found: ${actionId}`); const action = state.actions[index]; if ((action.resultFields || []).length >= 10) throw new ValidationError("An Action may have at most 10 Result Fields."); const field = createResultField({ ...input, position: input.position ?? action.resultFields.length, now: now() }); const next = { ...action, resultFields: [...(action.resultFields || []), field], updatedAt: now().toISOString() }; validateResultFields(next.resultFields, state.units); state.actions[index] = next; addHistory({ type: "definition", description: `Added Result Field: ${field.label}`, objectType: "resultField", objectId: field.id, snapshots: { actionId } }); return clone(field); }); },
    createBlock(input) { return repository.transaction(() => { const state = repository.getState(); const block = createBlock({ ...input, id: input.id || idFactory?.("block"), now: now() }); ensureUnique(state.blocks, block, "Block"); validateBlockGraph({ blocks: [...state.blocks, block], actions: state.actions }); state.blocks.push(block); addHistory({ type: "definition", description: `Created ${block.type} Block: ${block.name}`, objectType: "block", objectId: block.id }); return clone(block); }); },
    updateBlock(id, patch) { return repository.transaction(() => { const state = repository.getState(); const index = state.blocks.findIndex((block) => block.id === id); if (index < 0) throw new NotFoundError(`Block not found: ${id}`); const before = state.blocks[index]; const next = { ...before, ...clone(patch), id, updatedAt: now().toISOString() }; ensureUnique(state.blocks, next, "Block"); validateBlockGraph({ blocks: state.blocks.map((block, current) => current === index ? next : block), actions: state.actions }); state.blocks[index] = next; addHistory({ type: "definition", description: `Updated Block: ${next.name}`, objectType: "block", objectId: id, snapshots: { before: clone(before), after: clone(next) } }); return clone(next); }); },
    addRelationship(parentBlockId, input) { return repository.transaction(() => { const state = repository.getState(); const parent = state.blocks.find((block) => block.id === parentBlockId); if (!parent) throw new NotFoundError(`Block not found: ${parentBlockId}`); const relationship = createRelationship({ ...input, parentBlockId, position: input.position ?? parent.relationships.length, id: input.id || idFactory?.("relationship"), now: now() }); const next = { ...parent, relationships: [...parent.relationships, relationship], updatedAt: now().toISOString() }; validateBlockGraph({ blocks: state.blocks.map((block) => block.id === parentBlockId ? next : block), actions: state.actions }); Object.assign(parent, next); addHistory({ type: "definition", description: `Added relationship to ${parent.name}`, objectType: "relationship", objectId: relationship.id }); return clone(relationship); }); },
    logAction(input) { return repository.transaction(() => { const state = repository.getState(); const action = state.actions.find((candidate) => candidate.id === input.actionId); if (!action) throw new NotFoundError(`Action not found: ${input.actionId}`); const log = createActionLog({ ...input, action, finalizing: Boolean(input.finalizing), now: now(), units: state.units }); state.actionLogs.push(log); for (const reference of log.contextRefs || []) { const occurrence = state.occurrences.find((item) => item.id === reference.occurrenceId); if (occurrence && !occurrence.logIds.includes(log.id)) occurrence.logIds.push(log.id); } addHistory({ type: "action_log", description: `Logged ${action.name}`, objectType: "actionLog", objectId: log.id, actionId: action.id, snapshots: { action: log.actionSnapshot, results: log.resultValues.map((entry) => entry.snapshot) } }); emit(EVENT_TYPES.ACTION_LOGGED, { actionLogId: log.id, actionId: action.id }); return clone(log); }); },
    deleteActionLog(id) { return repository.transaction(() => { const state = repository.getState(); const index = state.actionLogs.findIndex((log) => log.id === id); if (index < 0) throw new NotFoundError(`Action Log not found: ${id}`); const [removed] = state.actionLogs.splice(index, 1); for (const occurrence of state.occurrences) occurrence.logIds = occurrence.logIds.filter((logId) => logId !== id); addHistory({ type: "action_log", description: `Deleted Action Log: ${removed.actionSnapshot?.name || removed.actionId}`, objectType: "actionLog", objectId: id, metadata: { factualSnapshotPreserved: true }, snapshots: { deleted: removed } }); emit(EVENT_TYPES.ACTION_LOG_DELETED, { actionLogId: id }); return clone(removed); }); },
    startRun(input) { return repository.transaction(() => { const state = repository.getState(); const block = state.blocks.find((candidate) => candidate.id === input.blockId); if (!block) throw new NotFoundError(`Block not found: ${input.blockId}`); const run = startDomainRun(createRun({ ...input, now: now(), snapshot: input.snapshot || { block: clone(block) } }), now()); state.runs.push(run); addHistory({ type: "run", description: `Started ${block.name}`, objectType: "run", objectId: run.id, snapshots: { run: run.snapshot } }); emit(EVENT_TYPES.RUN_STARTED, { runId: run.id, blockId: block.id }); return clone(run); }); },
    finishRun(id, status = "COMPLETED") { return repository.transaction(() => { const state = repository.getState(); const index = state.runs.findIndex((run) => run.id === id); if (index < 0) throw new NotFoundError(`Run not found: ${id}`); const run = finishDomainRun(state.runs[index], status, now()); state.runs[index] = run; addHistory({ type: "run", description: `Finished Run (${status})`, objectType: "run", objectId: id }); emit(EVENT_TYPES.RUN_FINISHED, { runId: id, status }); return clone(run); }); },
    createOccurrence(input) { return repository.transaction(() => { const state = repository.getState(); const occurrence = createOccurrence({ ...input, now: now() }); if (state.occurrences.some((item) => item.id === occurrence.id || item.relationshipId === occurrence.relationshipId && item.scheduledAt === occurrence.scheduledAt)) return clone(state.occurrences.find((item) => item.relationshipId === occurrence.relationshipId && item.scheduledAt === occurrence.scheduledAt)); state.occurrences.push(occurrence); emit(EVENT_TYPES.OCCURRENCE_CREATED, { occurrenceId: occurrence.id }); return clone(occurrence); }); },
    completeOccurrence(id) { return this.resolveOccurrence(id, "completed"); },
    skipOccurrence(id, reason = "") { return this.resolveOccurrence(id, "skipped", reason); },
    resolveOccurrence(id, status, reason = "") { return repository.transaction(() => { const state = repository.getState(); const occurrence = state.occurrences.find((item) => item.id === id); if (!occurrence) throw new NotFoundError(`Occurrence not found: ${id}`); occurrence.status = status; occurrence.reason = reason || null; occurrence.updatedAt = now().toISOString(); addHistory({ type: "occurrence", description: `${status} occurrence`, objectType: "occurrence", objectId: id, metadata: { reason } }); emit(status === "completed" ? EVENT_TYPES.OCCURRENCE_COMPLETED : EVENT_TYPES.OCCURRENCE_MISSED, { occurrenceId: id, status }); return clone(occurrence); }); },
    closePeriod(id, evaluation) { return repository.transaction(() => { const state = repository.getState(); const period = state.periods.find((item) => item.id === id); if (!period) throw new NotFoundError(`Period not found: ${id}`); if (period.status === "closed") return clone(period); period.status = "closed"; period.closedAt = now().toISOString(); period.evaluation = clone(evaluation); state.targetEvaluations.push({ periodId: id, ownerId: period.ownerId, evaluation: clone(evaluation), closedAt: period.closedAt, snapshot: clone(period.snapshot) }); addHistory({ type: "period", description: "Closed evaluation period", objectType: "period", objectId: id, snapshots: { evaluation } }); emit(EVENT_TYPES.PERIOD_CLOSED, { periodId: id }); return clone(period); }); },
    importPackage(packageValue, options = {}) { return repository.transaction(() => { const state = repository.getState(); const result = importPackage(packageValue, { ...options, existingState: state, now: now() }); repository.replaceState(result.state, { persist: false }); addHistory({ type: "import", description: "Imported SAMT package", metadata: { restorePoint: true } }); return result; }); }
  };
}
