import { ConflictError, NotFoundError, ValidationError } from "../shared/errors.js";
import { clone, normalizedKey } from "../shared/validation.js";
import { createAction, validateAction, versionResultFields } from "../domain/actions.js";
import { createCategory, createTag, validateTaxonomy } from "../domain/taxonomy.js";
import { createUnit, validateUnits } from "../domain/units.js";
import { createResultField, validateResultFields } from "../domain/results.js";
import { createActionLog } from "../domain/logs.js";
import { createBlock, setDefinitionStatus } from "../domain/blocks.js";
import { createRelationship, validateBlockGraph } from "../domain/relationships.js";
import { createOccurrence } from "../domain/occurrences.js";
import { createRun, startRun as startDomainRun, finishRun as finishDomainRun } from "../domain/runs.js";
import { pauseRun as pauseDomainRun, resumeRun as resumeDomainRun, cancelRun as cancelDomainRun } from "../domain/runs.js";
import { createActivation, pauseActivation as pauseDomainActivation, resumeActivation as resumeDomainActivation } from "../domain/activations.js";
import { appendHistory } from "../domain/history.js";
import { domainEvent, EVENT_TYPES } from "./events.js";
import { importPackage } from "../import-export/importer.js";

export function createCommands(repository, { clock = () => new Date(), idFactory = null } = {}) {
  const now = () => new Date(clock());
  function addHistory(event) { const state = repository.getState(); state.history = appendHistory(state.history || [], { ...event, timestamp: event.timestamp || now() }); }
  function emit(type, payload) { const state = repository.getState(); state.meta = state.meta || {}; state.meta.events = [...(state.meta.events || []), domainEvent(type, payload, now())].slice(-500); }
  function touch() { const state = repository.getState(); state.updatedAt = now().toISOString(); }
  function commandWasApplied(commandId) { if (!commandId) return false; const state = repository.getState(); state.meta = state.meta || {}; state.meta.appliedCommandIds = state.meta.appliedCommandIds || []; if (state.meta.appliedCommandIds.includes(commandId)) return true; state.meta.appliedCommandIds.push(commandId); state.meta.appliedCommandIds = state.meta.appliedCommandIds.slice(-1000); return false; }
  function ensureUnique(collection, item, label) { if (collection.some((candidate) => candidate.id !== item.id && normalizedKey(candidate.name) === normalizedKey(item.name))) throw new ConflictError(`${label} name already exists.`); }
  return {
    createCategory(input = {}) { return repository.transaction(() => { const state = repository.getState(); const category = createCategory({ ...input, id: input.id || idFactory?.("category"), now: now() }); ensureUnique(state.categories, category, "Category"); state.categories.push(category); validateTaxonomy(state); touch(); addHistory({ type: "definition", description: `Created Category: ${category.name}`, objectType: "category", objectId: category.id }); return clone(category); }); },
    updateCategory(id, patch = {}) { return repository.transaction(() => { const state = repository.getState(); const index = state.categories.findIndex((category) => category.id === id); if (index < 0) throw new NotFoundError(`Category not found: ${id}`); const before = state.categories[index]; const next = { ...before, ...clone(patch), id, updatedAt: now().toISOString() }; ensureUnique(state.categories, next, "Category"); validateTaxonomy({ ...state, categories: state.categories.map((category, current) => current === index ? next : category) }); state.categories[index] = next; touch(); addHistory({ type: "definition", description: `Updated Category: ${next.name}`, objectType: "category", objectId: id, snapshots: { before: clone(before), after: clone(next) } }); return clone(next); }); },
    archiveCategory(id) { return this.updateCategory(id, { status: "archived" }); },
    createTag(input = {}) { return repository.transaction(() => { const state = repository.getState(); const tag = createTag({ ...input, id: input.id || idFactory?.("tag"), now: now() }, state.categories); if (state.tags.some((candidate) => candidate.categoryId === tag.categoryId && normalizedKey(candidate.name) === normalizedKey(tag.name))) throw new ConflictError("Tag name already exists in that Category."); state.tags.push(tag); validateTaxonomy(state); touch(); addHistory({ type: "definition", description: `Created Tag: ${tag.name}`, objectType: "tag", objectId: tag.id }); return clone(tag); }); },
    updateTag(id, patch = {}) { return repository.transaction(() => { const state = repository.getState(); const index = state.tags.findIndex((tag) => tag.id === id); if (index < 0) throw new NotFoundError(`Tag not found: ${id}`); const before = state.tags[index]; const next = { ...before, ...clone(patch), id, updatedAt: now().toISOString() }; const candidate = state.tags.map((tag, current) => current === index ? next : tag); const ids = new Set(); const names = new Set(); for (const tag of candidate) { if (ids.has(tag.id)) throw new ConflictError("Tag IDs must remain unique."); ids.add(tag.id); const name = `${tag.categoryId}:${normalizedKey(tag.name)}`; if (names.has(name)) throw new ConflictError("Tag name already exists in that Category."); names.add(name); } validateTaxonomy({ ...state, tags: candidate }); state.tags[index] = next; touch(); addHistory({ type: "definition", description: `Updated Tag: ${next.name}`, objectType: "tag", objectId: id, snapshots: { before: clone(before), after: clone(next) } }); return clone(next); }); },
    archiveTag(id) { return this.updateTag(id, { status: "archived" }); },
    createUnit(input = {}) { return repository.transaction(() => { const state = repository.getState(); const unit = createUnit({ ...input, id: input.id || idFactory?.("unit"), now: now() }); if (state.units.some((candidate) => candidate.name.toLocaleLowerCase() === unit.name.toLocaleLowerCase() || candidate.symbol === unit.symbol || candidate.id === unit.id)) throw new ConflictError("Unit name, symbol or ID already exists."); const nextUnits = [...state.units, unit]; validateUnits(nextUnits); state.units.push(unit); touch(); addHistory({ type: "definition", description: `Created Unit: ${unit.name}`, objectType: "unit", objectId: unit.id }); return clone(unit); }); },
    updateUnit(id, patch = {}) { return repository.transaction(() => { const state = repository.getState(); const index = state.units.findIndex((unit) => unit.id === id); if (index < 0) throw new NotFoundError(`Unit not found: ${id}`); if (state.units[index].builtIn) throw new ConflictError("Built-in Units cannot be edited; create a custom Unit instead."); const before = state.units[index]; const next = { ...before, ...clone(patch), id, updatedAt: now().toISOString() }; if (state.units.some((unit, current) => current !== index && (unit.name.toLocaleLowerCase() === String(next.name).toLocaleLowerCase() || unit.symbol === next.symbol))) throw new ConflictError("Unit name or symbol already exists."); validateUnits(state.units.map((unit, current) => current === index ? next : unit)); state.units[index] = next; touch(); addHistory({ type: "definition", description: `Updated Unit: ${next.name}`, objectType: "unit", objectId: id, snapshots: { before: clone(before), after: clone(next) } }); return clone(next); }); },
    createAction(input = {}) { return repository.transaction(() => { const state = repository.getState(); const action = createAction({ ...input, id: input.id || idFactory?.("action"), now: now() }, { units: state.units, tags: state.tags, categories: state.categories }); validateAction(action, { units: state.units, tags: state.tags, categories: state.categories }); ensureUnique(state.actions, action, "Action"); state.actions.push(action); touch(); addHistory({ type: "definition", description: `Created Action: ${action.name}`, objectType: "action", objectId: action.id }); emit(EVENT_TYPES.DEFINITION_CHANGED, { objectType: "action", objectId: action.id }); return clone(action); }); },
    updateAction(id, patch = {}) { return repository.transaction(() => { const state = repository.getState(); const index = state.actions.findIndex((action) => action.id === id); if (index < 0) throw new NotFoundError(`Action not found: ${id}`); const before = state.actions[index]; const next = { ...before, ...clone(patch), id, resultFields: patch.resultFields ? versionResultFields(before.resultFields || [], patch.resultFields, now()) : before.resultFields, updatedAt: now().toISOString() }; ensureUnique(state.actions, next, "Action"); validateAction(next, { units: state.units, tags: state.tags, categories: state.categories }); state.actions[index] = next; touch(); addHistory({ type: "definition", description: `Updated Action: ${next.name}`, objectType: "action", objectId: id, snapshots: { before: clone(before), after: clone(next) } }); emit(EVENT_TYPES.DEFINITION_CHANGED, { objectType: "action", objectId: id }); return clone(next); }); },
    addResultField(actionId, input = {}) { return repository.transaction(() => { const state = repository.getState(); const index = state.actions.findIndex((action) => action.id === actionId); if (index < 0) throw new NotFoundError(`Action not found: ${actionId}`); const action = state.actions[index]; if ((action.resultFields || []).length >= 10) throw new ValidationError("An Action may have at most 10 Result Fields."); const field = createResultField({ ...input, position: input.position ?? action.resultFields.length, now: now() }); const next = { ...action, resultFields: [...(action.resultFields || []), field], updatedAt: now().toISOString() }; validateResultFields(next.resultFields, state.units); if (field.resultTagId && !state.tags.some((tag) => tag.id === field.resultTagId && ["result", "both"].includes(tag.scope))) throw new ValidationError("Result Field references an invalid Result Tag."); state.actions[index] = next; touch(); addHistory({ type: "definition", description: `Added Result Field: ${field.label}`, objectType: "resultField", objectId: field.id, snapshots: { actionId, field: clone(field) } }); emit(EVENT_TYPES.DEFINITION_CHANGED, { objectType: "resultField", objectId: field.id }); return clone(field); }); },
    createBlock(input = {}) { return repository.transaction(() => { const state = repository.getState(); const block = createBlock({ ...input, id: input.id || idFactory?.("block"), now: now() }); ensureUnique(state.blocks, block, "Block"); validateBlockGraph({ blocks: [...state.blocks, block], actions: state.actions }); state.blocks.push(block); touch(); addHistory({ type: "definition", description: `Created ${block.type} Block: ${block.name}`, objectType: "block", objectId: block.id }); return clone(block); }); },
    updateBlock(id, patch = {}) { return repository.transaction(() => { const state = repository.getState(); const index = state.blocks.findIndex((block) => block.id === id); if (index < 0) throw new NotFoundError(`Block not found: ${id}`); const before = state.blocks[index]; const next = { ...before, ...clone(patch), id, updatedAt: now().toISOString() }; ensureUnique(state.blocks, next, "Block"); validateBlockGraph({ blocks: state.blocks.map((block, current) => current === index ? next : block), actions: state.actions }); state.blocks[index] = next; touch(); addHistory({ type: "definition", description: `Updated Block: ${next.name}`, objectType: "block", objectId: id, snapshots: { before: clone(before), after: clone(next) } }); emit(EVENT_TYPES.DEFINITION_CHANGED, { objectType: "block", objectId: id }); return clone(next); }); },
    setBlockStatus(id, status) { return repository.transaction(() => { const state = repository.getState(); const index = state.blocks.findIndex((block) => block.id === id); if (index < 0) throw new NotFoundError(`Block not found: ${id}`); const before = state.blocks[index]; const next = setDefinitionStatus(before, status, now()); state.blocks[index] = next; touch(); addHistory({ type: "definition", description: `${status} Block: ${next.name}`, objectType: "block", objectId: id, snapshots: { before: clone(before), after: clone(next) } }); emit(status === "ACTIVE" ? EVENT_TYPES.BLOCK_ACTIVATED : EVENT_TYPES.BLOCK_PAUSED, { blockId: id, status }); return clone(next); }); },
    activateBlock(id) { return this.setBlockStatus(id, "ACTIVE"); },
    pauseBlock(id) { return this.setBlockStatus(id, "PAUSED"); },
    addRelationship(parentBlockId, input = {}) { return repository.transaction(() => { const state = repository.getState(); const parent = state.blocks.find((block) => block.id === parentBlockId); if (!parent) throw new NotFoundError(`Block not found: ${parentBlockId}`); const relationship = createRelationship({ ...input, parentBlockId, position: input.position ?? parent.relationships.length, id: input.id || idFactory?.("relationship"), now: now() }); const next = { ...parent, relationships: [...parent.relationships, relationship], updatedAt: now().toISOString() }; validateBlockGraph({ blocks: state.blocks.map((block) => block.id === parentBlockId ? next : block), actions: state.actions }); Object.assign(parent, next); touch(); addHistory({ type: "definition", description: `Added relationship to ${parent.name}`, objectType: "relationship", objectId: relationship.id }); return clone(relationship); }); },
    removeRelationship(parentBlockId, relationshipId) { return repository.transaction(() => { const state = repository.getState(); const parent = state.blocks.find((block) => block.id === parentBlockId); if (!parent) throw new NotFoundError(`Block not found: ${parentBlockId}`); const removed = parent.relationships.find((relationship) => relationship.id === relationshipId); if (!removed) throw new NotFoundError(`Relationship not found: ${relationshipId}`); parent.relationships = parent.relationships.filter((relationship) => relationship.id !== relationshipId); parent.updatedAt = now().toISOString(); touch(); addHistory({ type: "definition", description: `Removed relationship from ${parent.name}`, objectType: "relationship", objectId: relationshipId, snapshots: { removed: clone(removed) } }); return clone(removed); }); },
    logAction(input = {}) { return repository.transaction(() => { if (commandWasApplied(input.commandId)) return clone(repository.getState().actionLogs.find((log) => log.commandId === input.commandId)); const state = repository.getState(); const action = state.actions.find((candidate) => candidate.id === input.actionId); if (!action) throw new NotFoundError(`Action not found: ${input.actionId}`); const log = createActionLog({ ...input, action, finalizing: Boolean(input.finalizing), now: now(), units: state.units }); if (state.actionLogs.some((candidate) => candidate.id === log.id)) throw new ConflictError(`Action Log ID already exists: ${log.id}`); if (input.commandId) log.commandId = input.commandId; state.actionLogs.push(log); for (const reference of log.contextRefs || []) { const occurrence = state.occurrences.find((item) => item.id === reference.occurrenceId); if (occurrence && !occurrence.logIds.includes(log.id)) occurrence.logIds.push(log.id); } touch(); addHistory({ type: "action_log", description: `Logged ${action.name}`, objectType: "actionLog", objectId: log.id, actionId: action.id, snapshots: { action: log.actionSnapshot, results: log.resultValues.map((entry) => entry.snapshot) } }); emit(EVENT_TYPES.ACTION_LOGGED, { actionLogId: log.id, actionId: action.id }); return clone(log); }); },
    deleteActionLog(id) { return repository.transaction(() => { const state = repository.getState(); const index = state.actionLogs.findIndex((log) => log.id === id); if (index < 0) throw new NotFoundError(`Action Log not found: ${id}`); const [removed] = state.actionLogs.splice(index, 1); for (const occurrence of state.occurrences) occurrence.logIds = occurrence.logIds.filter((logId) => logId !== id); touch(); addHistory({ type: "action_log", description: `Deleted Action Log: ${removed.actionSnapshot?.name || removed.actionId}`, objectType: "actionLog", objectId: id, metadata: { factualSnapshotPreserved: true }, snapshots: { deleted: removed } }); emit(EVENT_TYPES.ACTION_LOG_DELETED, { actionLogId: id }); return clone(removed); }); },
    startRun(input) { return repository.transaction(() => { const state = repository.getState(); const block = state.blocks.find((candidate) => candidate.id === input.blockId); if (!block) throw new NotFoundError(`Block not found: ${input.blockId}`); const run = startDomainRun(createRun({ ...input, now: now(), snapshot: input.snapshot || { block: clone(block) } }), now()); state.runs.push(run); addHistory({ type: "run", description: `Started ${block.name}`, objectType: "run", objectId: run.id, snapshots: { run: run.snapshot } }); emit(EVENT_TYPES.RUN_STARTED, { runId: run.id, blockId: block.id }); return clone(run); }); },
    createActivation(input = {}) { return repository.transaction(() => { const state = repository.getState(); const block = state.blocks.find((candidate) => candidate.id === input.blockId); if (!block) throw new NotFoundError(`Block not found: ${input.blockId}`); const activation = createActivation({ ...input, id: input.id || idFactory?.("activation"), now: now() }); state.activations.push(activation); touch(); addHistory({ type: "activation", description: `Activated ${block.name}`, objectType: "activation", objectId: activation.id }); emit(EVENT_TYPES.BLOCK_ACTIVATED, { activationId: activation.id, blockId: block.id }); return clone(activation); }); },
    pauseActivation(id, options = {}) { return repository.transaction(() => { const state = repository.getState(); const index = state.activations.findIndex((activation) => activation.id === id); if (index < 0) throw new NotFoundError(`Activation not found: ${id}`); state.activations[index] = pauseDomainActivation(state.activations[index], { ...options, now: now() }); touch(); addHistory({ type: "activation", description: "Paused activation", objectType: "activation", objectId: id }); emit(EVENT_TYPES.BLOCK_PAUSED, { activationId: id }); return clone(state.activations[index]); }); },
    resumeActivation(id) { return repository.transaction(() => { const state = repository.getState(); const index = state.activations.findIndex((activation) => activation.id === id); if (index < 0) throw new NotFoundError(`Activation not found: ${id}`); state.activations[index] = resumeDomainActivation(state.activations[index], now()); touch(); addHistory({ type: "activation", description: "Resumed activation", objectType: "activation", objectId: id }); emit(EVENT_TYPES.BLOCK_ACTIVATED, { activationId: id, blockId: state.activations[index].blockId }); return clone(state.activations[index]); }); },
    finishRun(id, status = "COMPLETED") { return repository.transaction(() => { const state = repository.getState(); const index = state.runs.findIndex((run) => run.id === id); if (index < 0) throw new NotFoundError(`Run not found: ${id}`); const run = finishDomainRun(state.runs[index], status, now()); state.runs[index] = run; touch(); addHistory({ type: "run", description: `Finished Run (${status})`, objectType: "run", objectId: id }); emit(EVENT_TYPES.RUN_FINISHED, { runId: id, status }); return clone(run); }); },
    pauseRun(id) { return repository.transaction(() => { const state = repository.getState(); const index = state.runs.findIndex((run) => run.id === id); if (index < 0) throw new NotFoundError(`Run not found: ${id}`); state.runs[index] = pauseDomainRun(state.runs[index], now()); touch(); addHistory({ type: "run", description: "Paused Run", objectType: "run", objectId: id }); emit(EVENT_TYPES.RUN_PAUSED, { runId: id }); return clone(state.runs[index]); }); },
    resumeRun(id) { return repository.transaction(() => { const state = repository.getState(); const index = state.runs.findIndex((run) => run.id === id); if (index < 0) throw new NotFoundError(`Run not found: ${id}`); state.runs[index] = resumeDomainRun(state.runs[index], now()); touch(); addHistory({ type: "run", description: "Resumed Run", objectType: "run", objectId: id }); emit(EVENT_TYPES.RUN_RESUMED, { runId: id }); return clone(state.runs[index]); }); },
    cancelRun(id) { return repository.transaction(() => { const state = repository.getState(); const index = state.runs.findIndex((run) => run.id === id); if (index < 0) throw new NotFoundError(`Run not found: ${id}`); state.runs[index] = cancelDomainRun(state.runs[index], now()); touch(); addHistory({ type: "run", description: "Cancelled Run", objectType: "run", objectId: id }); emit(EVENT_TYPES.RUN_FINISHED, { runId: id, status: "CANCELLED" }); return clone(state.runs[index]); }); },
    createOccurrence(input = {}) { return repository.transaction(() => { const state = repository.getState(); const occurrence = createOccurrence({ ...input, now: now() }); const duplicate = state.occurrences.find((item) => item.id === occurrence.id || occurrence.scheduledAt != null && item.relationshipId === occurrence.relationshipId && item.scheduledAt === occurrence.scheduledAt); if (duplicate) return clone(duplicate); state.occurrences.push(occurrence); touch(); emit(EVENT_TYPES.OCCURRENCE_CREATED, { occurrenceId: occurrence.id }); return clone(occurrence); }); },
    completeOccurrence(id) { return this.resolveOccurrence(id, "completed"); },
    skipOccurrence(id, reason = "") { return this.resolveOccurrence(id, "skipped", reason); },
    resolveOccurrence(id, status, reason = "") { return repository.transaction(() => { const state = repository.getState(); const occurrence = state.occurrences.find((item) => item.id === id); if (!occurrence) throw new NotFoundError(`Occurrence not found: ${id}`); if (!["completed", "skipped", "missed", "expired", "excused", "not_applicable"].includes(status)) throw new ValidationError("Occurrence status is invalid."); const relationship = state.blocks.flatMap((block) => block.relationships || []).find((candidate) => candidate.id === occurrence.relationshipId); if (status === "skipped" && relationship?.config?.allowSkip === false) throw new ValidationError("Skipping this occurrence is not allowed."); if (status === "skipped" && relationship?.config?.requireSkipReason && !String(reason || "").trim()) throw new ValidationError("A skip reason is required."); occurrence.status = status; occurrence.reason = reason || null; occurrence.updatedAt = now().toISOString(); touch(); addHistory({ type: "occurrence", description: `${status} occurrence`, objectType: "occurrence", objectId: id, metadata: { reason } }); emit(status === "completed" ? EVENT_TYPES.OCCURRENCE_COMPLETED : status === "missed" ? EVENT_TYPES.OCCURRENCE_MISSED : EVENT_TYPES.OCCURRENCE_STATUS_CHANGED, { occurrenceId: id, status }); return clone(occurrence); }); },
    closePeriod(id, evaluation) { return repository.transaction(() => { const state = repository.getState(); const period = state.periods.find((item) => item.id === id); if (!period) throw new NotFoundError(`Period not found: ${id}`); if (period.status === "closed") return clone(period); period.status = "closed"; period.closedAt = now().toISOString(); period.evaluation = clone(evaluation); if (!state.targetEvaluations.some((item) => item.periodId === id)) state.targetEvaluations.push({ id: `${id}:evaluation`, periodId: id, ownerId: period.ownerId, evaluation: clone(evaluation), closedAt: period.closedAt, snapshot: clone(period.snapshot) }); touch(); addHistory({ type: "period", description: "Closed evaluation period", objectType: "period", objectId: id, snapshots: { evaluation } }); emit(EVENT_TYPES.PERIOD_CLOSED, { periodId: id }); return clone(period); }); },
    importPackage(packageValue, options = {}) { return repository.transaction(() => { const state = repository.getState(); const result = importPackage(packageValue, { ...options, existingState: state, now: now() }); const next = result.state; next.meta = next.meta || {}; next.meta.restorePoints = [...(next.meta.restorePoints || []), { createdAt: now().toISOString(), state: clone(result.restorePoint) }].slice(-5); repository.replaceState(next, { persist: false }); addHistory({ type: "import", description: "Imported SAMT package", metadata: { restorePoint: true } }); touch(); return result; }); }
  };
}
