export const EVENT_TYPES = Object.freeze({
  ACTION_LOGGED: "ACTION_LOGGED", ACTION_LOG_UPDATED: "ACTION_LOG_UPDATED", ACTION_LOG_DELETED: "ACTION_LOG_DELETED",
  RUN_STARTED: "RUN_STARTED", RUN_FINISHED: "RUN_FINISHED", RUN_PAUSED: "RUN_PAUSED", RUN_RESUMED: "RUN_RESUMED",
  OCCURRENCE_CREATED: "OCCURRENCE_CREATED", OCCURRENCE_COMPLETED: "OCCURRENCE_COMPLETED", OCCURRENCE_MISSED: "OCCURRENCE_MISSED",
  PERIOD_CLOSED: "PERIOD_CLOSED", TARGET_REACHED: "TARGET_REACHED", AVOID_FAILED: "AVOID_FAILED", CYCLE_ADVANCED: "CYCLE_ADVANCED",
  BLOCK_ACTIVATED: "BLOCK_ACTIVATED", BLOCK_PAUSED: "BLOCK_PAUSED", DEFINITION_CHANGED: "DEFINITION_CHANGED", SCOPE_CHANGED: "SCOPE_CHANGED"
});

export function domainEvent(type, payload = {}, now = new Date()) { return { type, occurredAt: new Date(now).toISOString(), payload }; }
