import { getDueOccurrences, getRunningRuns, getUpcomingOccurrences } from "./selectors.js";
import { calculateTargetProgress } from "../domain/targets.js";
import { evaluateAvoidFromLogs } from "../domain/avoid.js";
import { calculatePeriodBounds, isInPeriod, partsInTimeZone } from "../shared/dates.js";
import { getCurrentCyclePosition } from "../domain/cycles.js";

export function getHomeViewModel({ state, now = new Date(), timezone = state?.settings?.timezone || "UTC" } = {}) {
  const safeState = state || { actions: [], blocks: [], occurrences: [], actionLogs: [], settings: {} }; const running = getRunningRuns(safeState); const allDue = getDueOccurrences(safeState, now);
  const actionForOccurrence = (occurrence) => { const relationship = safeState.blocks.flatMap((block) => block.relationships || []).find((candidate) => candidate.id === occurrence.relationshipId); return safeState.actions.find((action) => action.id === (relationship?.refId || occurrence.snapshot?.actionId)); };
  const due = allDue.filter((occurrence) => actionForOccurrence(occurrence)?.direction !== "avoid"); const avoid = [];
  for (const action of safeState.actions || []) if (action.direction === "avoid") { const config = action.avoid || action.legacy?.avoid; const period = config?.period && !["session", "all_time"].includes(config.period) ? calculatePeriodBounds({ period: config.period, style: config.periodStyle || "calendar", at: now, timezone, weekStartsOn: config.weekStartsOn ?? safeState.settings?.weekStartsOn ?? 1 }) : null; let result = { actual: 0, logs: [] }; if (config) { try { result = evaluateAvoidFromLogs({ actionId: action.id, logs: safeState.actionLogs || [], config, period }); } catch (error) { result = { actual: 0, logs: [], status: "INVALID", error: error.message }; } } avoid.push({ actionId: action.id, name: action.name, status: config ? result.status : "UNCONFIGURED", ...result }); }
  const targetRows = (safeState.blocks || []).filter((block) => block.type === "target" && block.definitionStatus === "ACTIVE").map((target) => { const config = target.config || {}; const period = config.period && !["session", "all_time"].includes(config.period) ? calculatePeriodBounds({ period: config.period, style: config.periodStyle || "calendar", at: now, timezone: config.timezone || timezone, weekStartsOn: config.weekStartsOn ?? safeState.settings?.weekStartsOn ?? 1, customStart: config.customStart, customEnd: config.customEnd }) : null; let progress; try { progress = calculateTargetProgress({ target, logs: safeState.actionLogs || [], period, actions: safeState.actions || [], blocks: safeState.blocks || [], units: safeState.units || [] }); } catch (error) { progress = { status: "NOT_CONFIGURED", actual: null, targetValue: config.targetValue ?? 0, percentage: 0, error: error.message }; } return { targetId: target.id, name: target.name, period: config.period || "all_time", progress }; });
  const today = targetRows.filter((target) => target.period === "day" || target.period === "session"); const thisWeek = targetRows.filter((target) => target.period === "week");
  const cycleNow = (safeState.blocks || []).filter((block) => block.type === "cycle" && block.definitionStatus === "ACTIVE").map((cycle) => ({ cycleId: cycle.id, name: cycle.name, position: getCurrentCyclePosition(cycle) }));
  const projects = (safeState.blocks || []).filter((block) => block.type === "project" && block.definitionStatus === "ACTIVE"); const primaryId = safeState.settings?.primaryProjectId; const currentProject = projects.find((project) => project.id === primaryId) || null;
  const localToday = partsInTimeZone(now, timezone); const todayKey = `${localToday.year}-${String(localToday.month).padStart(2, "0")}-${String(localToday.day).padStart(2, "0")}`; const laterToday = getUpcomingOccurrences(safeState, now, 20).filter((occurrence) => String(occurrence.scheduledAt || "").startsWith(todayKey) && actionForOccurrence(occurrence)?.direction !== "avoid").slice(0, 5);
  const overdue = due.filter((occurrence) => occurrence.status === "overdue"); const dueNow = due.filter((occurrence) => occurrence.status !== "overdue"); const upcoming = getUpcomingOccurrences(safeState, now, 5);
  let choice; if (running.length) choice = { type: "running", items: running }; else if (overdue.length) choice = { type: "overdue", items: overdue }; else if (dueNow.length) choice = { type: "due", items: dueNow }; else if (cycleNow.some((cycle) => cycle.position)) choice = { type: "cycle", items: cycleNow }; else if (today.some((target) => target.progress?.percentage >= 75 && !target.progress?.reached)) choice = { type: "target", items: today.filter((target) => target.progress?.percentage >= 75 && !target.progress?.reached) }; else choice = { type: "next", items: upcoming };
  return { now: { at: new Date(now).toISOString(), choice, running, cycle: cycleNow }, due: { overdue, dueNow, laterToday }, avoid, today, thisWeek, currentProject, upcoming, timezone };
}
