import { getHomeViewModel } from "./home.js";
import { getAnalysisViewModel } from "./analysis.js";
import { getActionById, getBlockById, getBlockChildren, getBlockDescendants, getActiveBlocks, getRunningRuns, getDueOccurrences, getUpcomingOccurrences } from "./selectors.js";
import { calculateTargetProgress } from "../domain/targets.js";
import { evaluateAvoidFromLogs } from "../domain/avoid.js";

export function createQueries(repository, { clock = () => new Date() } = {}) {
  const state = () => repository.getState();
  return { getActionById: (id) => getActionById(state(), id), getBlockById: (id) => getBlockById(state(), id), getBlockChildren: (id) => getBlockChildren(state(), id), getBlockDescendants: (id) => getBlockDescendants(state(), id), getActiveBlocks: () => getActiveBlocks(state()), getRunningRuns: () => getRunningRuns(state()), getDueOccurrences: () => getDueOccurrences(state(), clock()), getUpcomingOccurrences: (limit = 5) => getUpcomingOccurrences(state(), clock(), limit), getTargetProgress: (targetId, options = {}) => { const current = state(); const target = getBlockById(current, targetId); const resultFieldId = options.resultField?.id || target?.config?.sourceResultFieldId; const resultField = options.resultField || current.actions?.flatMap((action) => action.resultFields || []).find((field) => field.id === resultFieldId) || null; return calculateTargetProgress({ target, logs: current.actionLogs, actions: current.actions, blocks: current.blocks, units: current.units, resultField, descendantBlockIds: target?.config?.descendantBlockIds || (target?.config?.sourceBlockId ? getBlockDescendants(current, target.config.sourceBlockId) : []), ...options }); }, getAvoidStatus: (actionId, config, period = null) => evaluateAvoidFromLogs({ actionId, config, period, logs: state().actionLogs }), getHomeViewModel: (options = {}) => getHomeViewModel({ state: state(), now: options.now || clock(), timezone: options.timezone || state().settings.timezone }), getAnalysisViewModel: (options = {}) => getAnalysisViewModel({ state: state(), ...options }) };
}
