import {TYPES,RESULT_TYPES,emptyState,validate,execute,reconcile,periodBounds,localKey,overview,actionAnalysis,home,alarmRequests,backup,importBackup} from './engine.js';

const KEY='samt.android.v3';const root=document.getElementById('app');
const H=(value)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=(v)=>v?new Date(v).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const inputDateTime=(value=Date.now())=>{const x=new Date(value),pad=n=>String(n).padStart(2,'0');return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}T${pad(x.getHours())}:${pad(x.getMinutes())}`;};
const short=(v)=>v?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—';
const title=s=>s.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const names={home:'Today',actions:'Actions',blocks:'Blocks',log:'Quick log',activity:'History & analysis',settings:'Settings'};
const nav=[['home','⌖','Today'],['actions','◉','Actions'],['blocks','▦','Blocks'],['activity','▤','Activity'],['settings','⚙','Settings']];
const icons={collection:'▤',action_list:'☑',routine:'↻',workflow:'⇢',project:'◇',cycle:'◉',target:'◎'};
const colors={collection:'#7c65c7',action_list:'#5483d0',routine:'#1d9a84',workflow:'#986cca',project:'#d88354',cycle:'#466bd7',target:'#b68431'};
let state,recovery=null,route='home',detail=null,modal=null,toast=null,tab='all',activityTab='history',settingsTab='general',draftResults=[],actionReturn=null,temporary=false;
try{const native=window.SamtAndroid?.loadState?.();const raw=native||localStorage.getItem(KEY);state=raw?JSON.parse(raw):emptyState();validate(state);}catch(e){recovery=e;state=emptyState();}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));temporary=false;}catch(e){temporary=true;show('Storage unavailable: export a backup before closing.','bad');}}
function save(){persist();syncNative();render();}
function refreshFromPhone(){
 const raw=window.SamtAndroid?.loadState?.();if(!raw)return;
 const onPhone=JSON.parse(raw);validate(onPhone);
 if(Date.parse(onPhone.meta?.updatedAt||0)>Date.parse(state.meta?.updatedAt||0))state=onPhone;
}
function command(type,extra={}){try{refreshFromPhone();const result=execute(state,{type,...extra},Date.now());state=result.state;save();return result.value;}catch(e){show(e.message||String(e),'bad');return null;}}
function syncNative(){if(!window.SamtAndroid)return;try{if(!window.SamtAndroid.saveState(JSON.stringify(state)))throw new Error('Phone storage refused the change.');window.SamtAndroid.scheduleAlarms(JSON.stringify(alarmRequests(state,Date.now())));}catch(e){temporary=true;show(`Phone storage or alarm sync needs attention: ${e.message}`,'bad');}}
function show(message,kind='good'){toast={message,kind};render();setTimeout(()=>{toast=null;render()},3600);}
function navigate(to,chosen=null){route=to;detail=chosen;modal=null;render();window.scrollTo({top:0,behavior:'instant'});}
function theme(){const preference=state.settings.appearance||'system';return preference==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):preference;}
function btn(label,action,extra='',style=''){return `<button type="button" class="btn ${style}" data-action="${H(action)}" ${extra}>${H(label)}</button>`;}
function field(label,name,value='',type='text',hint='',options=''){
 const input=type==='select'?`<select name="${H(name)}" id="f_${H(name)}">${options}</select>`:type==='textarea'?`<textarea name="${H(name)}" id="f_${H(name)}">${H(value)}</textarea>`:
   `<input id="f_${H(name)}" name="${H(name)}" type="${H(type)}" value="${H(value)}" ${type==='number'?'step="any"':''}>`;
 return `<div class="field"><label for="f_${H(name)}">${H(label)}</label>${input}${hint?`<small>${H(hint)}</small>`:''}</div>`;
}
function opts(values,selected){return values.map(([value,label])=>`<option value="${H(value)}" ${String(value)===String(selected)?'selected':''}>${H(label)}</option>`).join('');}
function select(label,name,values,selected){return field(label,name,'','select','',opts(values,selected));}
function check(label,name,checked){return `<label class="field check"><input type="checkbox" name="${H(name)}" ${checked?'checked':''}>${H(label)}</label>`;}
function orb(symbol,color){return `<span class="orb" style="--item-color:${H(color||state.settings.accent)}">${H(symbol)}</span>`;}
function empty(label,action,text){return `<div class="empty"><strong>${H(label)}</strong>${H(text||'Start by adding your first item.')}<div class="actions" style="justify-content:center;margin-top:13px">${btn('Add one',action,'','primary')}</div></div>`;}
function status(value){const t=String(value||'OPEN').toUpperCase();const cls=['COMPLETED','REACHED','DONE','ACTIVE'].includes(t)?'good':['MISSED','FAILED'].includes(t)?'bad':'warn';return `<span class="badge ${cls}">${H(title(t))}</span>`;}
function top(){return `<header class="top"><div><div class="eyebrow">${H(new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'}))}</div><h1>${H(names[route])}</h1></div><div class="top-actions"><button class="iconbtn" type="button" data-action="theme" title="Change appearance">${theme()==='dark'?'☼':'☾'}</button><button class="iconbtn" type="button" data-action="quick-log" title="Quick log">＋</button><div class="avatar">S</div></div></header>`;}
function shell(content){const links=nav.map(([key,icon,label])=>`<button type="button" data-route="${key}" class="${route===key?'active':''}"><span class="ico">${icon}</span><span>${label}</span></button>`).join('');return `<div class="shell"><aside class="side"><div class="brand"><span class="mark">⌖</span><span><strong>SAMT</strong><small>سَمْت · Direction</small></span></div><nav class="nav">${links}</nav><div class="side-foot">Your progress, your direction.<br>Saved on this phone.</div></aside><main class="main">${top()}${temporary?'<div class="data-note danger-note">Storage is unavailable. Export a backup before leaving.</div>':''}${content}</main><nav class="bottom" aria-label="Main navigation">${links}</nav></div>${modal?modalHtml():''}${toast?`<div class="toast" role="status">${H(toast.message)}</div>`:''}`;}
function modalHtml(){return `<div class="modal-shade" data-action="close-modal"><div class="modal" role="dialog" aria-modal="true" aria-label="${H(modal.heading)}" data-stop="1"><div class="modal-head"><div><div class="eyebrow">SAMT · ${H(modal.eyebrow||'Build')}</div><h2>${H(modal.heading)}</h2></div><button type="button" class="iconbtn" data-action="close-modal" aria-label="Close">×</button></div><form id="editor" data-form="${H(modal.kind)}">${modal.body}<div class="modal-foot">${btn('Cancel','close-modal') }<button type="submit" class="btn primary">${H(modal.submit||'Save')}</button></div></form></div></div>`;}
function open(kind,heading,body,submit='Save',data={}){modal={kind,heading,body,submit,data};render();}
function render(){document.documentElement.dataset.theme=theme();document.documentElement.style.setProperty('--accent',state.settings.accent||'#147d86');const page=recovery?recoveryPage():route==='home'?homePage():route==='actions'?actionsPage():route==='blocks'?blocksPage():route==='log'?logPage():route==='activity'?activityPage():settingsPage();root.innerHTML=shell(page);}
function recoveryPage(){return `<section class="stack"><div class="card"><h2>Open your SAMT data safely</h2><p>Saved data could not be read: ${H(recovery?.message)}. No data has been overwritten.</p><div class="actions">${btn('Import a backup','import-backup','','primary')}${btn('Start empty','recover-empty')}</div></div></section>`;}
function homePage(){const data=home(state,Date.now()),summary=overview(state),openRuns=state.runs.filter(x=>x.status==='IN_PROGRESS');
 const nowText=data.now?data.now.blockSnapshot?.name||data.now.itemSnapshot?.name||'Next up':'Make the first move';
 const due=data.due.slice(0,5),avoid=data.avoid.slice(0,4);
 return `<div class="stack"><div class="cols"><div class="card hero"><div class="eyebrow">Your bearing today</div><h2>${H(nowText)}</h2><p>${data.now?'Your active work is ready. One logged action can count everywhere it belongs.':'Build an Action or a Block, then start tracking what matters.'}</p><div class="actions">${btn('Quick log','quick-log')}${btn('Explore Blocks','go-blocks')}</div></div><div class="card"><div class="eyebrow">At a glance</div><div class="stat-row" style="margin-top:22px"><div><div class="stat-number">${summary.logs}</div><div class="stat-label">Action logs</div></div><div><div class="stat-number">${openRuns.length}</div><div class="stat-label">Active runs</div></div><div><div class="stat-number">${data.due.length}</div><div class="stat-label">Due items</div></div></div><div class="separator"></div><div class="small muted">London calendar · ${H(localKey(Date.now(),state.settings.timezone))}</div></div></div>
 <div class="cols"><div class="stack"><section><div class="section"><h2>Due & overdue</h2><span class="badge">${due.length} shown</span></div><div class="card">${due.length?due.map(o=>occRow(o)).join(''):empty('All clear','new-list','Scheduled entries will appear here.')}</div></section>
 <section><div class="section"><h2>Current runs</h2></div><div class="card">${openRuns.length?openRuns.slice(0,5).map(runRow).join(''):empty('No active runs','go-blocks','Start a Routine, Workflow or Project.')}</div></section></div><div class="stack"><div class="card"><div class="card-heading"><h2>Avoid & limit</h2>${btn('View Actions','go-actions','','tiny')}</div>${avoid.length?avoid.map(a=>`<div class="row">${orb('◌','#c67567')}<div class="row-main"><strong>${H(a.name)}</strong><small>Review at period end</small></div></div>`).join(''):'<p class="small">Avoid Actions you create will appear here. A clean period can succeed without inventing a log.</p>'}</div><div class="card"><div class="card-heading"><h2>This week</h2><span class="badge">${data.week.length} entries</span></div>${data.week.slice(0,4).map(occRow).join('')||'<p class="small">Your upcoming week is open.</p>'}</div><div class="card"><div class="card-heading"><h2>Current project</h2></div>${data.project?runRow(data.project):'<p class="small">No project Run is active.</p>'}</div></div></div></div>`;
}
function occRow(o){const isTodo=o.entrySnapshot?.kind==='Todo';return `<div class="row">${orb(isTodo?'☑':'◉',isTodo?'#6385ca':state.settings.accent)}<div class="row-main"><strong>${H(o.itemSnapshot?.name||o.entrySnapshot?.name)}</strong><small>${H(date(o.dueAt))} · ${H(state.blocks.find(b=>b.id===o.blockId)?.name||'Action List')}</small></div>${['OPEN','OVERDUE','CARRIED'].includes(o.status)?`${isTodo?btn('Done','todo',`data-id="${H(o.id)}"`,'tiny'):btn('Log','log-occ',`data-id="${H(o.id)}"`,'tiny')}${btn('⋯','occ-options',`data-id="${H(o.id)}"`,'tiny')}`:status(o.status)}</div>`;}
function runRow(r){return `<div class="row">${orb(icons[r.type]||'↻',colors[r.type])}<div class="row-main"><strong>${H(r.blockSnapshot?.name)}</strong><small>${r.children.filter(c=>c.status==='DONE').length}/${r.children.length} done ${r.deadlineAt?'· Ends '+H(date(r.deadlineAt)):''}</small></div>${btn('Open','open-run',`data-id="${H(r.id)}"`,'tiny')}</div>`;}
function actionsPage(){const active=state.actions.filter(x=>x.status!=='ARCHIVED');return `<div class="stack"><div class="section"><div><h2>Your Actions</h2><span class="small muted">Define once · log everywhere</span></div>${btn('+ Action','new-action','','primary')}</div>${active.length?`<div class="grid">${active.map(a=>`<article class="card" style="border-top:3px solid ${H(a.direction==='Avoid'?'#ca7869':state.settings.accent)}"><div class="card-heading">${orb(a.direction==='Avoid'?'◌':'◉',a.direction==='Avoid'?'#ca7869':state.settings.accent)}${status(a.status)}</div><h2>${H(a.name)}</h2><p class="small">${H(a.description||`${a.completion?.type==='time'?'Time':'Quantity'} · ${a.resultFields.length} result fields`)}</p><div class="actions">${btn('Log','log-action',`data-id="${H(a.id)}"`,'tiny primary')}${btn('History','action-history',`data-id="${H(a.id)}"`,'tiny')}${btn('Edit','edit-action',`data-id="${H(a.id)}"`,'tiny')}</div></article>`).join('')}</div>`:empty('Actions start here','new-action','Define what you do, measure or avoid.')}</div>`;}
function blocksPage(){const type=tab,blocks=state.blocks.filter(b=>b.status!=='ARCHIVED'&&(type==='all'||b.type===type));
 if(detail){const b=state.blocks.find(x=>x.id===detail);return b?blockDetail(b):empty('Block not found','go-blocks');}
 const filters=[['all','All'],...TYPES.map(t=>[t,title(t)])];
 return `<div class="stack"><div class="section"><div><h2>Blocks</h2><span class="small muted">Seven distinct ways to organise your life</span></div>${btn('+ Block','new-block','','primary')}</div><div class="choicebar">${filters.map(([k,label])=>`<button type="button" data-filter="${H(k)}" class="${tab===k?'active':''}">${H(label)}</button>`).join('')}</div>${blocks.length?`<div class="grid">${blocks.map(b=>`<article class="card" style="border-top:3px solid ${H(colors[b.type])}"><div class="card-heading">${orb(icons[b.type],colors[b.type])}<span class="badge">${H(title(b.type))}</span></div><h2>${H(b.name)}</h2><p class="small">${H(b.description||`${(b.relationships||[]).length+(b.entries||[]).length} linked items`)}</p><div class="actions">${btn('Open','block-detail',`data-id="${H(b.id)}"`,'tiny primary')}${btn('Edit','edit-block',`data-id="${H(b.id)}"`,'tiny')}</div></article>`).join('')}</div>`:empty('No Blocks here','new-block','Create a Collection, Action List, Routine, Workflow, Project, Cycle or Target.')}</div>`;
}
function blockDetail(b){const runs=state.runs.filter(x=>x.blockId===b.id).slice(-5).reverse(),act=state.activations.find(x=>x.blockId===b.id),periods=state.periods.filter(x=>x.blockId===b.id).slice(-3).reverse(),cycle=state.cycles.find(x=>x.blockId===b.id);
 return `<div class="stack"><div class="section"><div>${btn('← Blocks','back-blocks','','tiny')}<div style="height:12px"></div><h2>${H(b.name)}</h2><span class="badge">${H(title(b.type))}</span></div><div class="actions">${btn('Edit','edit-block',`data-id="${H(b.id)}"`)}${b.type!=='collection'?btn('Activate','activate',`data-id="${H(b.id)}"`,'primary'):''}</div></div>
 ${b.description?`<div class="data-note">${H(b.description)}</div>`:''}<div class="cols"><div class="stack"><div class="card"><div class="card-heading"><h2>${b.type==='action_list'?'Entries':'Relationships'}</h2>${btn(b.type==='action_list'?'+ Entry':'+ Child',b.type==='action_list'?'add-entry':'add-child',`data-id="${H(b.id)}"`,'tiny')}</div>${b.type==='action_list'?(b.entries||[]).map(e=>`<div class="row entry-row">${orb(e.kind==='Todo'?'☑':'◉',colors[b.type])}<div class="row-main"><strong>${H(e.kind==='Todo'?e.name:state.actions.find(x=>x.id===e.refId)?.name||'Missing Action')}</strong><small>${H(e.kind)} · ${H(e.schedule?.mode||'manual')} ${e.schedule?.time?H(e.schedule.time):''} ${e.paused?'· Paused':''}</small><div class="entry-controls">${e.schedule?.mode==='manual'?btn('Start now','start-manual',`data-block="${H(b.id)}" data-id="${H(e.id)}"`,'tiny primary'):''}${btn(e.paused?'Resume':'Pause','pause-entry',`data-block="${H(b.id)}" data-id="${H(e.id)}"`,'tiny')}${(e.offPeriods||[]).some(p=>p.untilNotified&&!p.notifiedAt)?btn('End Off','end-off',`data-block="${H(b.id)}" data-id="${H(e.id)}"`,'tiny'):btn('Off','off-period',`data-block="${H(b.id)}" data-id="${H(e.id)}"`,'tiny')}</div></div></div>`).join('')||'<p class="small">Add Action or Todo entries to schedule them.</p>':(b.relationships||[]).map(r=>`<div class="row">${orb(r.kind==='Action'?'◉':'▦',colors[b.type])}<div class="row-main"><strong>${H((r.kind==='Action'?state.actions:state.blocks).find(x=>x.id===r.refId)?.name||'Missing')}</strong><small>${r.required?'Required':'Optional'} · ${H(r.kind)}</small></div></div>`).join('')||'<p class="small">Link Actions or Blocks.</p>'}</div>
 ${b.type==='cycle'&&cycle?`<div class="card"><h2>Current cycle</h2><p>Round ${cycle.round} · position ${cycle.index+1} of ${cycle.sequence.length}</p><div class="actions">${btn('Completed','resolve-cycle',`data-id="${H(b.id)}" data-outcome="COMPLETED"`,'primary')}${btn('Missed','resolve-cycle',`data-id="${H(b.id)}" data-outcome="MISSED"`)}</div></div>`:''}
 ${b.type==='target'&&periods.length?`<div class="card"><h2>Target periods</h2>${periods.map(p=>`<div class="row"><div class="row-main"><strong>${H(short(p.start))} – ${H(short(p.end))}</strong><small>${H(String(p.actual))} / ${H(String(p.target))} · ${p.target?Math.round(100*p.actual/p.target):0}%</small></div>${status(p.status)}</div>`).join('')}</div>`:''}</div><div class="stack"><div class="card"><h2>State</h2><div class="row"><div class="row-main"><strong>Definition</strong><small>${H(b.status)}</small></div>${status(b.status)}</div><div class="row"><div class="row-main"><strong>Activation</strong><small>${H(act?.schedule?.period||'Manual')}</small></div>${status(act?.status||'INACTIVE')}</div>${['routine','workflow','project'].includes(b.type)?btn('Run now','run-now',`data-id="${H(b.id)}"`,'primary'):''}</div>${runs.length?`<div class="card"><h2>Recent runs</h2>${runs.map(runRow).join('')}</div>`:''}</div></div></div>`;
}
function logPage(){return `<div class="stack"><div class="section"><h2>Quick log</h2></div><div class="data-note">One real event creates one Action Log. Choose where it happened so every relevant Block can reflect it.</div>${state.actions.length?`<div class="grid">${state.actions.filter(x=>x.status!=='ARCHIVED').map(a=>`<div class="card"><div class="card-heading">${orb('◉',state.settings.accent)}<span class="badge">${H(a.completion.type)}</span></div><h2>${H(a.name)}</h2>${btn('Log this Action','log-action',`data-id="${H(a.id)}"`,'primary')}</div>`).join('')}</div>`:empty('Define an Action first','new-action')}</div>`;}
function activityPage(){const t=activityTab,stats=overview(state);return `<div class="stack"><div class="choicebar">${[['history','History'],['analysis','Analysis'],['reviews','Reviews'],['capacity','Capacity']].map(([key,label])=>`<button type="button" data-activity="${key}" class="${t===key?'active':''}">${label}</button>`).join('')}</div>${t==='history'?`<div class="card"><h2>History</h2>${state.history.length?state.history.slice().reverse().slice(0,120).map(h=>`<div class="row">${orb('•',state.settings.accent)}<div class="row-main"><strong>${H(title(h.event))}</strong><small>${H(date(h.at))} · ${H(h.displayName||state.actions.find(a=>a.id===h.actionId)?.name||state.blocks.find(b=>b.id===h.blockId)?.name||'')}</small></div></div>`).join(''):'<p>No activity yet. Factual logs and outcomes will appear here.</p>'}</div>`:
 t==='analysis'?`<div class="stack"><div class="stat-row">${[['Unique logs',stats.logs],['Unique minutes',stats.uniqueMinutes],['Completed runs',stats.completedRuns]].map(([name,v])=>`<div class="card metric"><div class="stat-number">${v}</div><div class="stat-label">${name}</div></div>`).join('')}</div><div class="card"><h2>Action analysis</h2>${state.actions.map(a=>{const x=actionAnalysis(state,a.id);return `<div class="row">${orb('◉',state.settings.accent)}<div class="row-main"><strong>${H(a.name)}</strong><small>${x.logs} logs · ${x.minutes} minutes · ${x.quantity} quantity</small></div></div>`}).join('')||'<p>Analysis begins when you log an Action.</p>'}</div></div>`:
 t==='reviews'?`<div class="stack"><div class="section"><h2>Reviews</h2>${btn('+ Review','new-review','','primary')}</div>${state.reviews.slice().reverse().map(x=>`<div class="card"><div class="small muted">${H(short(x.at))} · ${H(x.period)}</div><h2>${H(x.highlights||'Reflection')}</h2><p>${H(x.notes)}</p><strong>Next: ${H(x.next)}</strong></div>`).join('')||empty('No reviews yet','new-review')}</div>`:
 `<div class="card"><h2>Capacity</h2><p>Planning guidance only. Your history records what you actually did.</p><div class="stat-number">${H(state.settings.capacityHours)} h</div><div class="stat-label">Hours planned per week</div>${btn('Adjust in Settings','go-settings')}</div>`}</div>`;}
function settingsPage(){const tabs=[['general','General'],['build','Build'],['data','Data & storage'],['bin','Bin'],['app','App']];return `<div class="stack"><div class="choicebar">${tabs.map(([k,label])=>`<button type="button" data-settings="${k}" class="${settingsTab===k?'active':''}">${label}</button>`).join('')}</div>${settingsTab==='general'?`<div class="cols"><div class="card"><h2>Appearance</h2><p class="small">Colours help you recognise your areas of life. Choose how SAMT looks on your phone.</p><form data-form="settings"><div class="form-grid">${select('Display mode','appearance',[['system','Follow phone'],['light','Light'],['dark','Dark']],state.settings.appearance)}${field('Accent colour','accent',state.settings.accent,'color')}</div>${select('Week begins','weekStartsOn',[[1,'Monday'],[0,'Sunday']],state.settings.weekStartsOn)}${field('Timezone','timezone',state.settings.timezone,'text','Routines close at local midnight; current default: Europe/London.')}${field('Planned weekly capacity (hours)','capacityHours',state.settings.capacityHours,'number')}<button class="btn primary" type="submit">Save settings</button></form></div><div class="card"><h2>What the settings change</h2><p>Theme and accent affect the interface. Timezone and week start define new calendar periods; historical timestamps stay factual.</p><div class="data-note">Current period: ${H(short(periodBounds('weekly',Date.now(),state.settings).start))} to ${H(short(periodBounds('weekly',Date.now(),state.settings).end))}</div></div></div>`:
 settingsTab==='build'?`<div class="grid">${[['categories','Categories'],['tags','Tags'],['units','Units']].map(([kind,label])=>`<div class="card"><div class="card-heading"><h2>${label}</h2>${btn('+ Add',`new-${kind}`,'','tiny')}</div>${state[kind].map(x=>`<div class="row"><div class="row-main"><strong>${H(x.name)}</strong><small>${H(x.dimension||x.symbol||'')}</small></div>${btn('Archive','archive',`data-kind="${kind}" data-id="${H(x.id)}"`,'tiny')}</div>`).join('')||'<p class="small">None yet.</p>'}</div>`).join('')}</div>`:
 settingsTab==='data'?`<div class="cols"><div class="card"><h2>Backups</h2><p>Keep a copy before moving phones or uninstalling SAMT. Imports are checked before your current data changes.</p><div class="actions">${btn('Export JSON','export-backup','','primary')}${btn('Import JSON','import-backup')}</div></div><div class="card"><h2>Data manager</h2><p>Manage definitions in Build or archive them from their detail view. Your history stays factual.</p><div class="pill-row">${[['Actions',state.actions.length],['Blocks',state.blocks.length],['Logs',state.actionLogs.length],['Runs',state.runs.length],['History',state.history.length]].map(([name,n])=>`<span class="badge">${name}: ${n}</span>`).join('')}</div><div class="separator"></div>${btn('Create restore point','restore-point')}${btn('Clear everything','clear-everything','','danger')}</div></div>`:
 settingsTab==='bin'?`<div class="card"><h2>Recently deleted</h2>${state.bin.map(item=>`<div class="row"><div class="row-main"><strong>${H(item.snapshot.name)}</strong><small>${H(item.kind)} · ${H(short(item.deletedAt))}</small></div>${btn('Restore','restore',`data-id="${H(item.id)}"`,'tiny')}${btn('Delete permanently','permanent-delete',`data-id="${H(item.id)}"`,'tiny danger')}</div>`).join('')||'<p>The Bin is empty.</p>'}</div>`:`<div class="card"><h2>SAMT for Android</h2><p>Version 0.1 · local on this phone. Alarms need Android notification and alarm access to run at exact times while the app is closed.</p><div id="permissions">${window.SamtAndroid?(()=>{try{const p=JSON.parse(window.SamtAndroid.permissions());return `Notifications: ${p.notifications?'allowed':'needs permission'} · Exact alarms: ${p.exact?'allowed':'needs permission'}`;}catch(e){return 'Phone permissions unavailable.'}})():'Browser preview: phone permissions available in the Android APK.'}</div><div class="actions" style="margin-top:15px">${window.SamtAndroid?`${btn('Allow notifications','notification-permission')}${btn('Allow exact alarms','alarm-permission')}`:''}</div></div>`}</div>`;}

function actionEditor(action=null){draftResults=action?structuredClone(action.resultFields):[];const tags=state.tags.map(tag=>check(tag.name,`tag_${tag.id}`,action?.tagIds?.includes(tag.id))).join('');
 open('action',action?'Edit Action':'New Action',`${field('Name','name',action?.name||'')}${field('Description','description',action?.description||'','textarea')}<div class="form-grid">${select('Direction','direction',[['Do','Do'],['Avoid','Avoid / limit']],action?.direction||'Do')}${select('Completion','completion',[['quantity','Quantity'],['time','Time']],action?.completion?.type||'quantity')}</div><div class="form-grid">${field('Quantity target','target',action?.completion?.target||1,'number')}${field('Minimum minutes','minutes',action?.completion?.minimumMinutes||0,'number')}</div><div class="field"><label>Tags</label><div class="pill-row">${tags||'<span class="small muted">Create Tags in Settings → Build.</span>'}</div></div><div class="separator"></div><div class="card-heading"><h2>Results (${draftResults.length}/10)</h2>${btn('+ Result','add-result','','tiny')}</div><div id="result-list">${resultDraftHtml()}</div>`,action?'Save Action':'Create Action',{id:action?.id});}
function resultDraftHtml(){return draftResults.map((r,i)=>`<div class="row"><div class="row-main"><strong>${H(r.label)}</strong><small>${H(title(r.type))} · ${r.required?'Required':'Optional'}</small></div>${btn('Remove','remove-result',`data-index="${i}"`,'tiny danger')}</div>`).join('')||'<p class="small">Optional fields let you record scores, measurements and other results on each log.</p>';}
function blockEditor(block=null){const type=block?.type||'routine',period=block?.config?.period||'manual';open('block',block?'Edit Block':'New Block',`${field('Name','name',block?.name||'')}${field('Description','description',block?.description||'','textarea')}${select('Block type','type',TYPES.map(t=>[t,title(t)]),type)}<div class="form-grid">${select('Calendar period','period',[['manual','Manual'],['daily','Daily'],['weekly','Weekly'],['monthly','Monthly'],['yearly','Yearly']],period)}${select('Target measure','metric',[['count','Log count'],['minutes','Minutes'],['quantity','Quantity'],['result','Result value']],block?.config?.metric||'count')}</div>${field('Target amount','target',block?.config?.target??1,'number')}<div class="data-note">Collection groups definitions; Action List creates Occurrences; Routine, Workflow and Project use Runs; Cycle keeps its position; Target evaluates Periods.</div>`,block?'Save Block':'Create Block',{id:block?.id});}
function entryEditor(block){const options=state.actions.map(a=>[a.id,a.name]);open('entry','Action List entry',`${select('Entry type','kind',[['Todo','Todo'],['Action','Action']],options.length?'Action':'Todo')}${field('Todo title','name','')}${select('Linked Action','refId',[['','Choose an Action'],...options],'')}${select('Schedule','mode',[['manual','Manual'],['once','Once'],['daily','Daily'],['weekly','Weekly'],['monthly','Monthly'],['yearly','Yearly'],['interval','Interval'],['specific_dates','Specific dates']],'daily')}<div class="form-grid">${field('Time (local)','time','09:00','time')}${field('Once at (ISO date/time)','at','', 'datetime-local')}${field('First active date','activeFrom','', 'datetime-local')}${field('Last active date','activeUntil','', 'datetime-local')}</div><div class="form-grid">${field('Weekdays (0=Sun, comma separated)','weekdays','1,2,3,4,5')}${field('Specific dates (comma separated)','dates','')}${field('Every N days or weeks','every',1,'number')}${select('Interval unit','unit',[['days','Days'],['weeks','Weeks']],'days')}</div><div class="form-grid">${field('Deadline after due (minutes)','deadlineMinutes','')}${select('Unfinished item','unfinished',[['stay_overdue','Stay overdue'],['expire','Expire / missed'],['carry_forward','Carry forward']],'stay_overdue')}</div>${field('Reminders (minutes before, comma separated)','reminders','15')}${check('Alarm at due time','alarm',false)}`, 'Add entry',{blockId:block.id});}
function logEditor(action,contextId=null){const resultFields=(action.resultFields||[]).map(f=>f.type==='choice'?select(f.label,`result_${f.id}`,[['','Choose'],...(f.options||[]).map(o=>[o.id,o.label])],''):
 field(`${f.label}${f.required?' *':''}`,`result_${f.id}`,'',f.type==='text'?'text':'number')).join('');
 const contexts=state.runs.filter(r=>r.status==='IN_PROGRESS').flatMap(r=>r.children.filter(c=>c.refId===action.id&&c.status==='OPEN').map(c=>[c.id,`${r.blockSnapshot.name} · ${c.definitionSnapshot?.name||action.name}`]));
 const occ=state.occurrences.filter(o=>o.itemSnapshot?.id===action.id&&['OPEN','OVERDUE','CARRIED'].includes(o.status)).map(o=>[o.id,`${state.blocks.find(b=>b.id===o.blockId)?.name||'List'} · ${date(o.dueAt)}`]);
 open('log',`Log ${action.name}`,`${field('When it happened','occurredAt',inputDateTime(),'datetime-local')}<div class="form-grid">${field('Quantity','quantity',action.completion?.type==='quantity'?1:0,'number')}${field('Minutes','durationMinutes',action.completion?.type==='time'?1:0,'number')}</div>${resultFields}${field('Notes','notes','','textarea')}<div class="field"><label>Linked contexts</label>${[...contexts,...occ].map(([key,label])=>check(label,`context_${key}`,key===contextId)).join('')||'<small>No current Runs or Occurrences require this Action; your Log still counts in History and Analysis.</small>'}</div>`, 'Save log',{actionId:action.id});}
function modalFor(action,node){const id=node.dataset.id,blockId=node.dataset.block;switch(action){
 case 'new-action':actionEditor();break;case 'edit-action':actionEditor(state.actions.find(x=>x.id===id));break;
 case 'new-block':case 'new-list':blockEditor();break;case 'edit-block':blockEditor(state.blocks.find(x=>x.id===id));break;
 case 'add-entry':entryEditor(state.blocks.find(x=>x.id===id));break;
 case 'add-child':open('child','Link a child',`${select('Child kind','kind',[['Action','Action'],['Block','Block']],'Action')}${select('Action','actionId',state.actions.map(a=>[a.id,a.name]),state.actions[0]?.id)}${select('Block','blockId',state.blocks.filter(b=>b.id!==id).map(b=>[b.id,b.name]),'')}${check('Required for completion','required',true)}${field('Cycle weight','weight',1,'number')}`,'Add child',{blockId:id});break;
 case 'activate':open('activation','Activate Block',`${select('Schedule','period',[['manual','Manual'],['daily','Every local day'],['weekly','Every local week']],state.blocks.find(b=>b.id===id)?.config?.period||'manual')}<p class="small">Daily and weekly Routine Runs close at the calendar boundary and generate the next Run automatically.</p>`,'Activate',{blockId:id});break;
 case 'log-action':logEditor(state.actions.find(x=>x.id===id));break;
 case 'log-occ':{const occ=state.occurrences.find(x=>x.id===id);logEditor(state.actions.find(a=>a.id===occ.itemSnapshot.id),occ.id);break;}
 case 'quick-log':if(state.actions.length)navigate('log');else actionEditor();break;
 case 'new-review':open('review','Write a review',`${select('Period','period',[['day','Daily'],['week','Weekly'],['month','Monthly']],'week')}${field('Highlights','highlights')}${field('Reflection','notes','','textarea')}${field('What next?','next','','textarea')}`,'Save review');break;
 case 'off-period':open('off','Set an Off Period',`${field('Start','start',inputDateTime(),'datetime-local')}${field('End (leave blank for until notified)','end','','datetime-local')}${check('Until notified / ended by me','untilNotified',false)}`,'Set Off',{blockId,entryId:id});break;
 case 'occ-options':open('occ-options','Occurrence options',`<p>Skip resolves only this occurrence. Snooze moves its alarm while the item remains open.</p><div class="actions">${btn('Snooze 10 minutes','snooze-occ',`data-id="${H(id)}"`)}${btn('Skip this one','skip-occ',`data-id="${H(id)}"`,'danger')}</div>`,'Close',{occurrenceId:id});break;
 case 'new-categories':open('category','New Category',`${field('Name','name')}${field('Colour','color','#1d9a84','color')}`,'Create');break;
 case 'new-tags':open('tag','New Tag',`${field('Name','name')}${select('Category','categoryId',state.categories.map(c=>[c.id,c.name]),state.categories[0]?.id)}`,'Create');break;
 case 'new-units':open('unit','New Unit',`${field('Name','name')}${field('Symbol','symbol')}${field('Dimension (e.g. mass, distance)','dimension')}`,'Create');break;
 case 'add-result':if(draftResults.length<10){actionReturn={values:formObject(document.querySelector('#editor')),id:modal.data.id,results:structuredClone(draftResults)};open('result','Add a Result field',`${field('Label','label')}${select('Type','type',RESULT_TYPES.map(t=>[t,title(t)]),'score')}${check('Required','required',false)}<div class="form-grid">${field('Minimum','minimum',0,'number')}${field('Maximum','maximum',10,'number')}</div>${select('Unit','unitId',[['','None'],...state.units.map(u=>[u.id,`${u.name} (${u.symbol||''})`])],'')}${field('Choice options (comma separated)','options','')}`,'Add field');}break;
 default:break;
}}
function formObject(form){const data=new FormData(form),obj=Object.fromEntries(data.entries());for(const el of form.querySelectorAll('input[type=checkbox]'))obj[el.name]=el.checked;return obj;}
function submit(form){const m=modal;if(!m)return;const d=formObject(form);let value;switch(m.kind){
 case 'occ-options':case 'run':modal=null;render();return;
 case 'category':value=command('ADD_DEFINITION',{kind:'categories',data:{name:d.name.trim(),color:d.color}});break;
 case 'tag':value=command('ADD_DEFINITION',{kind:'tags',data:{name:d.name.trim(),categoryId:d.categoryId}});break;
 case 'unit':value=command('ADD_DEFINITION',{kind:'units',data:{name:d.name.trim(),symbol:d.symbol,dimension:d.dimension}});break;
 case 'result':{
   if(!d.label.trim())throw new Error('Give this Result a name.');
   const field={id:`result_${crypto.randomUUID()}`,label:d.label.trim(),type:d.type,required:!!d.required,minimum:d.minimum===''?null:Number(d.minimum),maximum:d.maximum===''?null:Number(d.maximum),unitId:d.unitId||null,options:d.options?d.options.split(',').map(label=>({id:`option_${crypto.randomUUID()}`,label:label.trim()})).filter(x=>x.label):[]};
   const draft=actionReturn;draft.results.push(field);actionEditor(draft.id?state.actions.find(x=>x.id===draft.id):null);draftResults=draft.results;
   const restored=document.querySelector('#editor');for(const [name,v] of Object.entries(draft.values)){const el=restored.elements.namedItem(name);if(el){if(el.type==='checkbox')el.checked=!!v;else el.value=v;}}
   document.querySelector('#result-list').innerHTML=resultDraftHtml();actionReturn=null;return;
 }
 case 'action':{
   const tags=Object.entries(d).filter(([k,v])=>k.startsWith('tag_')&&v).map(([k])=>k.slice(4));
   const data={name:d.name.trim(),description:d.description.trim(),direction:d.direction,completion:d.completion==='time'?{type:'time',minimumMinutes:Number(d.minutes)||0}:{type:'quantity',target:Number(d.target)||1},resultFields:structuredClone(draftResults),tagIds:tags};
   value=m.data.id?command('EDIT_DEFINITION',{kind:'actions',id:m.data.id,changes:data}):command('ADD_DEFINITION',{kind:'actions',data});break;
 }
 case 'block':{
   const data={name:d.name.trim(),description:d.description.trim(),type:d.type,config:{...(m.data.id?state.blocks.find(b=>b.id===m.data.id)?.config:{}),period:d.period,metric:d.metric,target:Number(d.target)||0}};
   value=m.data.id?command('EDIT_DEFINITION',{kind:'blocks',id:m.data.id,changes:data}):command('ADD_DEFINITION',{kind:'blocks',data});break;
 }
 case 'child':value=command('ADD_RELATIONSHIP',{blockId:m.data.blockId,kind:d.kind,refId:d.kind==='Action'?d.actionId:d.blockId,required:!!d.required,weight:Number(d.weight)||1});break;
 case 'entry':{
   const schedule={mode:d.mode,time:d.time,at:d.at?new Date(d.at).toISOString():null,weekdays:d.weekdays.split(',').map(Number),dates:d.dates.split(',').map(x=>x.trim()).filter(Boolean),every:Number(d.every)||1,unit:d.unit};
   value=command('ADD_ENTRY',{blockId:m.data.blockId,kind:d.kind,refId:d.kind==='Action'?d.refId:null,name:d.name.trim(),schedule,activeFrom:d.activeFrom?new Date(d.activeFrom).toISOString():null,activeUntil:d.activeUntil?new Date(d.activeUntil).toISOString():null,deadlineMinutes:d.deadlineMinutes===''?null:Number(d.deadlineMinutes),unfinished:d.unfinished,reminderMinutes:d.reminders.split(',').map(Number).filter(x=>x>=0),alarm:!!d.alarm});break;
 }
 case 'activation':value=command('ACTIVATE',{blockId:m.data.blockId,schedule:{period:d.period}});break;
 case 'log':{
   const results={},contexts=[];for(const [k,v] of Object.entries(d)){if(k.startsWith('result_'))results[k.slice(7)]=v;if(k.startsWith('context_')&&v)contexts.push(k.slice(8));}
   value=command('LOG_ACTION',{actionId:m.data.actionId,occurredAt:d.occurredAt?new Date(d.occurredAt).toISOString():null,quantity:Number(d.quantity)||0,durationMinutes:Number(d.durationMinutes)||0,results,contexts,notes:d.notes});break;
 }
 case 'review':value=command('ADD_REVIEW',{period:d.period,highlights:d.highlights,notes:d.notes,next:d.next});break;
 case 'off':value=command('OFF_PERIOD',{blockId:m.data.blockId,entryId:m.data.entryId,start:new Date(d.start).toISOString(),end:d.end?new Date(d.end).toISOString():null,untilNotified:!!d.untilNotified});break;
 default:return;
 }
 if(value){modal=null;render();show('Saved.');}
}
function exportFile(){const content=backup(state,Date.now()),name=`SAMT-backup-${localKey(Date.now(),state.settings.timezone)}.json`;if(window.SamtAndroid){window.SamtAndroid.exportFile(name,'application/json',content);return;}const blob=new Blob([content],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importFile(file){try{const incoming=importBackup(await file.text());const prev=structuredClone(state);incoming.restorePoints.push({id:`restore_${crypto.randomUUID()}`,at:new Date().toISOString(),reason:'before import',state:prev});state=incoming;recovery=null;save();show('Backup imported.');}catch(e){show(`Import cancelled: ${e.message}`,'bad');}}
window.SamtReceiveImport=text=>{try{const incoming=importBackup(text),prev=structuredClone(state);incoming.restorePoints.push({id:`restore_${crypto.randomUUID()}`,at:new Date().toISOString(),reason:'before import',state:prev});state=incoming;recovery=null;save();show('Backup imported.');}catch(e){show(e.message,'bad');}};
const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.addEventListener('change',()=>{if(input.files?.[0])importFile(input.files[0]);input.value='';});document.body.appendChild(input);
root.addEventListener('click',e=>{const node=e.target.closest('[data-route],[data-action],[data-filter],[data-activity],[data-settings]');if(!node)return;
 if(node.dataset.stop)return;if(node.dataset.route){navigate(node.dataset.route);return;}
 if(node.dataset.filter){tab=node.dataset.filter;render();return;}if(node.dataset.activity){activityTab=node.dataset.activity;render();return;}if(node.dataset.settings){settingsTab=node.dataset.settings;render();return;}
 const a=node.dataset.action,id=node.dataset.id;
 if(a==='close-modal'){if(modal?.kind==='result'&&actionReturn){const draft=actionReturn;actionEditor(draft.id?state.actions.find(x=>x.id===draft.id):null);draftResults=draft.results;const restored=document.querySelector('#editor');for(const [name,v] of Object.entries(draft.values)){const el=restored.elements.namedItem(name);if(el){if(el.type==='checkbox')el.checked=!!v;else el.value=v;}}document.querySelector('#result-list').innerHTML=resultDraftHtml();actionReturn=null;}else{modal=null;render();}return;}if(a==='theme'){const modes=['system','light','dark'],next=modes[(modes.indexOf(state.settings.appearance)+1)%3];command('SET_SETTINGS',{changes:{appearance:next}});show(`Appearance: ${title(next)}`);return;}
 if(a==='go-blocks'||a==='back-blocks'){navigate('blocks');return;}if(a==='go-actions'){navigate('actions');return;}if(a==='go-settings'){settingsTab='general';navigate('settings');return;}
 if(a==='block-detail'){navigate('blocks',id);return;}if(a==='todo'){command('COMPLETE_TODO',{occurrenceId:id});return;}
 if(a==='start-manual'){command('START_MANUAL_OCCURRENCE',{blockId:node.dataset.block,entryId:id});return;}
 if(a==='pause-entry'){
   const entry=state.blocks.find(b=>b.id===node.dataset.block)?.entries.find(e=>e.id===id);
   if(entry)command('PAUSE_ENTRY',{blockId:node.dataset.block,entryId:id,paused:!entry.paused});return;
 }
 if(a==='end-off'){
   const entry=state.blocks.find(b=>b.id===node.dataset.block)?.entries.find(e=>e.id===id);
   const off=entry?.offPeriods?.find(p=>p.untilNotified&&!p.notifiedAt);
   if(off)command('STOP_OFF_PERIOD',{blockId:node.dataset.block,entryId:id,offId:off.id});return;
 }
 if(a==='snooze-occ'){command('SNOOZE',{occurrenceId:id,minutes:10});modal=null;render();return;}if(a==='skip-occ'){if(confirm('Skip this occurrence only?')){command('SKIP_OCCURRENCE',{occurrenceId:id});modal=null;render();}return;}
 if(a==='resolve-cycle'){command('RESOLVE_CYCLE',{blockId:id,outcome:node.dataset.outcome});return;}if(a==='run-now'){command('RUN_NOW',{blockId:id});return;}
 if(a==='open-run'){const r=state.runs.find(x=>x.id===id);if(!r)return;open('run',r.blockSnapshot.name,`<p>${H(r.status)} · Started ${H(date(r.startedAt))}</p>${r.children.map(c=>`<div class="row">${orb(c.status==='DONE'?'✓':'○',colors[r.type])}<div class="row-main"><strong>${H(c.definitionSnapshot?.name)}</strong><small>${c.required?'Required':'Optional'} · ${H(c.status)}</small></div>${c.status==='OPEN'?btn('Done','done-child',`data-run="${H(r.id)}" data-id="${H(c.id)}"`,'tiny'):''}</div>`).join('')}`,'Close',{runId:id});return;}
 if(a==='done-child'){command('RESOLVE_CHILD',{runId:node.dataset.run,childId:id,status:'DONE'});modal=null;return;}
 if(a==='action-history'){activityTab='analysis';navigate('activity');return;}
 if(a==='archive'){if(confirm('Archive this definition? Its history will remain.'))command('ARCHIVE',{kind:node.dataset.kind,id});return;}
 if(a==='restore'){command('RESTORE',{binId:id});return;}if(a==='permanent-delete'){if(confirm('Permanently delete this Bin item?'))command('PERMANENT_DELETE',{binId:id});return;}
 if(a==='export-backup'){exportFile();return;}if(a==='import-backup'){if(window.SamtAndroid)window.SamtAndroid.importFile();else input.click();return;}
 if(a==='restore-point'){state.restorePoints.push({id:`restore_${crypto.randomUUID()}`,at:new Date().toISOString(),reason:'manual',state:structuredClone({...state,restorePoints:[]})});save();show('Restore point saved.');return;}
 if(a==='clear-everything'){if(confirm('Export a backup first. Clear all SAMT data on this phone?')&&confirm('This will remove all Actions, Blocks, Logs and History. Continue?')){exportFile();state=emptyState();save();show('SAMT is empty and ready.');}return;}
 if(a==='recover-empty'){if(confirm('Replace unreadable stored data with a new empty SAMT?')){state=emptyState();recovery=null;save();}return;}
 if(a==='alarm-permission'){window.SamtAndroid?.requestAlarmPermission();return;}
 if(a==='notification-permission'){window.SamtAndroid?.requestNotifications();return;}
 if(a==='remove-result'){draftResults.splice(Number(node.dataset.index),1);document.querySelector('#result-list').innerHTML=resultDraftHtml();return;}
 if(a)modalFor(a,node);
});
root.addEventListener('submit',e=>{e.preventDefault();const form=e.target;if(form.dataset.form==='settings'){const d=formObject(form);command('SET_SETTINGS',{changes:{appearance:d.appearance,accent:d.accent,timezone:d.timezone,weekStartsOn:Number(d.weekStartsOn),capacityHours:Number(d.capacityHours)}});show('Settings saved.');return;}try{submit(form);}catch(error){show(error.message,'bad');}});
root.addEventListener('click',e=>{if(e.target.classList.contains('modal-shade')){modal=null;render();}});
matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>render());
if(!recovery){state=reconcile(state,Date.now());persist();syncNative();}
window.SamtResume=()=>{try{const raw=window.SamtAndroid?.loadState?.();if(raw){const onPhone=JSON.parse(raw);validate(onPhone);state=reconcile(onPhone,Date.now());persist();syncNative();render();}}catch(e){show(`Phone data could not be refreshed: ${e.message}`,'bad');}};
window.SamtFileError=message=>show(message,'bad');
setInterval(()=>{if(!recovery){try{refreshFromPhone();const next=reconcile(state,Date.now());if(JSON.stringify(next)!==JSON.stringify(state)){state=next;save();}}catch(e){show(e.message,'bad');}}},60000);
render();
