import { badge, escapeHtml, titleCase } from "./format.js";

export function renderActionsView(actions) {
  return `<main class="page-shell"><header class="page-head"><div class="page-head-copy"><span class="eyebrow">Library</span><h1>Actions</h1><p class="muted">Reusable factual activities. One real event creates one log.</p></div><button class="btn btn-primary" data-action="new-action">New Action</button></header><section class="card">${actions.length ? actions.map((action) => `<article class="row"><div class="row-main"><div class="inline"><a class="row-title" href="#/actions/${encodeURIComponent(action.id)}">${escapeHtml(action.name)}</a>${badge(action.status)}${action.direction === "avoid" ? badge("avoid") : ""}</div><div class="row-meta"><span>${escapeHtml(titleCase(action.completion?.method || "quantity"))}</span><span>${escapeHtml(titleCase(action.result?.mode || "none"))} result</span></div></div><div class="inline"><button class="btn btn-primary btn-small" data-action="log-action" data-id="${escapeHtml(action.id)}">Log</button><button class="btn btn-small" data-action="edit-action" data-id="${escapeHtml(action.id)}">Edit</button><button class="btn btn-ghost btn-small" data-action="delete-action" data-id="${escapeHtml(action.id)}">Delete</button></div></article>`).join("") : '<div class="empty"><h2>No Actions yet</h2><p>Create the first thing you want to track.</p></div>'}</section></main>`;
}

export function renderActionDetailView(action, logs) {
  if (!action) return '<main class="page-shell"><div class="empty">Action not found.</div></main>';
  return `<main class="page-shell"><header class="page-head"><div class="page-head-copy"><span class="eyebrow">Action</span><h1>${escapeHtml(action.name)}</h1><p class="muted">${escapeHtml(action.description || "No description.")}</p></div><div class="inline"><button class="btn btn-primary" data-action="log-action" data-id="${escapeHtml(action.id)}">Log</button><button class="btn" data-action="edit-action" data-id="${escapeHtml(action.id)}">Edit</button></div></header><section class="card"><div class="section-head"><h2>Factual logs</h2><span class="badge">${logs.length}</span></div>${logs.length ? logs.slice().reverse().map((log) => `<article class="row"><div class="row-main"><strong>${escapeHtml(new Date(log.timestamp).toLocaleString())}</strong><div class="row-meta"><span>${log.durationPerformed != null ? `${escapeHtml(log.durationPerformed)} minutes` : `${escapeHtml(log.quantityPerformed)} quantity`}</span>${log.note ? `<span>${escapeHtml(log.note)}</span>` : ""}</div></div><div class="inline"><button class="btn btn-small" data-action="edit-log" data-id="${escapeHtml(log.id)}">Correct</button><button class="btn btn-ghost btn-small" data-action="delete-log" data-id="${escapeHtml(log.id)}">Delete log</button></div></article>`).join("") : '<div class="empty">Nothing logged yet.</div>'}</section></main>`;
}
