import { badge, escapeHtml, formatDateTime, formatMetric } from "./format.js";

function occurrenceRows(items) {
  if (!items.length) return '<div class="empty">Nothing here right now.</div>';
  return `<div>${items.map((item) => `<article class="row"><div class="row-main"><div class="inline"><a class="row-title" href="#/actions/${encodeURIComponent(item.actionId)}">${escapeHtml(item.actionName)}</a>${badge(item.status)}</div><div class="row-meta"><span>${escapeHtml(item.blockName)}</span>${item.dueAt ? `<span>${escapeHtml(formatDateTime(item.dueAt, true))}</span>` : ""}</div></div><div class="inline"><button class="btn btn-primary btn-small" data-action="log-action" data-id="${escapeHtml(item.actionId)}">Log</button></div></article>`).join("")}</div>`;
}

function targetRows(items) {
  if (!items.length) return '<div class="empty">No active targets for this period.</div>';
  return `<div class="stack">${items.map((item) => item.kind === "occurrence_context"
    ? `<article class="card card-plain"><div class="split"><a class="row-title" href="#/blocks/${encodeURIComponent(item.id)}">${escapeHtml(item.name)}</a>${badge(item.status)}</div><div class="metric-value">${escapeHtml(item.completed)} <span class="muted">/ ${escapeHtml(item.total)} completed</span></div><div class="progress" aria-label="${Math.round(item.percentage)} percent"><span style="--progress:${Math.min(100, item.percentage)}%"></span></div><p class="muted">${item.due ? `${escapeHtml(item.due)} due` : item.upcoming ? `${escapeHtml(item.upcoming)} upcoming` : "Current daily state"}</p></article>`
    : `<article class="card card-plain"><div class="split"><a class="row-title" href="#/blocks/${encodeURIComponent(item.id)}">${escapeHtml(item.name)}</a>${badge(item.status)}</div><div class="metric-value">${escapeHtml(formatMetric(item.actual, item.metric))} <span class="muted">/ ${escapeHtml(formatMetric(item.target, item.metric))}</span></div><div class="progress" aria-label="${Math.round(item.percentage)} percent"><span style="--progress:${Math.min(100, item.percentage)}%"></span></div><p class="muted">${item.over > 0 ? `${escapeHtml(formatMetric(item.over, item.metric))} over target` : `${escapeHtml(formatMetric(item.remaining, item.metric))} remaining`}</p></article>`).join("")}</div>`;
}

function avoidRows(items) {
  if (!items.length) return '<div class="empty">No Avoid contexts are active.</div>';
  return `<div>${items.map((item) => `<article class="row"><div class="row-main"><div class="inline"><strong class="row-title">${escapeHtml(item.name)}</strong>${badge(item.status)}</div><div class="row-meta"><span>${escapeHtml(formatMetric(item.actual, item.metric))}</span>${item.score != null ? `<span>Score ${escapeHtml(item.score)}%</span>` : ""}${item.failureLoad ? `<span>${escapeHtml(item.failureLoad)}% failure load</span>` : ""}</div></div>${item.actionId ? `<button class="btn btn-small" data-action="log-action" data-id="${escapeHtml(item.actionId)}">Record</button>` : `<a class="btn btn-small" href="#/blocks/${encodeURIComponent(item.blockId || item.id)}">Open</a>`}</article>`).join("")}</div>`;
}

export function renderHomeView(model) {
  const nowText = model.nowChoices.length ? model.nowChoices.map((item) => escapeHtml(item.label)).join(" · ") : "Nothing is demanding attention.";
  const firstUse = model.firstUse
    ? `<section class="card section first-use"><span class="eyebrow">Ready to use</span><h2>${escapeHtml(model.firstUse.title)}</h2><p class="muted">${escapeHtml(model.firstUse.message)}</p><div class="inline"><button class="btn btn-primary" data-action="new-action">Create first Action</button><button class="btn" data-action="new-block">Create first Block</button></div></section>`
    : "";
  const project = model.currentProject ? `<section class="card section"><div class="section-head"><div><span class="eyebrow">Primary project</span><h2><a href="#/blocks/${encodeURIComponent(model.currentProject.id)}">${escapeHtml(model.currentProject.name)}</a></h2></div>${model.currentProject.overdue ? badge("overdue") : model.currentProject.runningRunId ? badge("running") : badge(model.currentProject.status)}</div>${model.currentProject.progress?.percentage != null ? `<div class="progress" aria-label="${Math.round(model.currentProject.progress.percentage)} percent"><span style="--progress:${Math.min(100, model.currentProject.progress.percentage)}%"></span></div>` : ""}</section>` : "";
  return `<main class="page-shell"><header class="page-head"><div class="page-head-copy"><span class="eyebrow">Today</span><h1>Your next move</h1><p class="muted">${nowText}</p></div><div class="inline"><button class="btn btn-primary" data-action="quick-log">+ Log</button><a class="btn" href="#/action-lists">Open Action Lists</a></div></header>${firstUse}<div class="summary-strip"><div class="metric"><span class="muted">Due now</span><strong class="metric-value">${model.due.dueNow.length}</strong></div><div class="metric"><span class="muted">Overdue</span><strong class="metric-value">${model.due.overdue.length}</strong></div><div class="metric"><span class="muted">Running</span><strong class="metric-value">${model.running.length}</strong></div></div>${project}<div class="home-layout section"><div class="stack"><section class="card"><div class="section-head"><h2>Due</h2><span class="badge">${model.due.overdue.length + model.due.dueNow.length + model.due.laterToday.length}</span></div>${occurrenceRows([...model.due.overdue, ...model.due.dueNow, ...model.due.laterToday])}</section><section class="card"><div class="section-head"><h2>Avoid</h2></div>${avoidRows(model.avoid)}</section></div><div class="stack"><section class="card"><div class="section-head"><h2>Today</h2></div>${targetRows(model.today)}</section><section class="card"><div class="section-head"><h2>This week</h2></div>${targetRows(model.thisWeek)}</section><section class="card"><div class="section-head"><h2>Upcoming</h2></div>${occurrenceRows(model.upcoming)}</section></div></div></main>`;
}
