import { escapeHtml } from "./format.js";

export function renderSettingsView(state) {
  const mode = state.settings?.appearanceMode || "system";
  const savedCount = (state.actions || []).length + (state.blocks || []).length + (state.actionLogs || []).length + (state.history || []).length;
  const latestRestore = [...(state.restorePoints || [])].reverse()[0];
  const bin = state.bin || [];
  const binRows = bin.length ? bin.map((item) => `<article class="row"><div class="row-main"><strong>${escapeHtml(item.nameSnapshot)}</strong><div class="row-meta"><span>${escapeHtml(item.objectType)}</span><span>Restore before ${escapeHtml(new Date(item.purgeAt).toLocaleDateString())}</span></div></div><button class="btn btn-small" data-action="restore-definition" data-id="${escapeHtml(item.id)}">Restore</button></article>`).join("") : '<div class="empty">The Bin is empty.</div>';
  return `<main class="page-shell"><header class="page-head"><div class="page-head-copy"><span class="eyebrow">System</span><h1>Settings</h1><p class="muted">Storage, portability and simple reference-client presentation.</p></div></header><section class="grid-2"><article class="card section"><div><span class="eyebrow">Appearance placeholder</span><h2>Reference UI</h2><p class="muted">Design and colour controls are intentionally disabled until a future client replaces this UI.</p></div><div class="field"><span class="label">Design</span><button class="btn" disabled>Default</button></div><div class="field"><span class="label">Mode</span><div class="segmented">${["light", "dark", "system"].map((item) => `<button type="button" class="btn" aria-pressed="${mode === item}" data-action="set-mode" data-mode="${item}">${escapeHtml(item[0].toUpperCase() + item.slice(1))}</button>`).join("")}</div></div><div class="field"><span class="label">Colour placeholders</span><div class="inline"><button class="btn" disabled>Blue</button><button class="btn" disabled>Green</button><button class="btn" disabled>Gold</button></div></div></article><article class="card section"><div><span class="eyebrow">Storage continuity</span><h2>Your existing SAMT database</h2><p class="muted">The legacy IndexedDB database, object store and recovery keys are unchanged.</p></div><div class="metric"><span class="muted">Saved records</span><strong class="metric-value">${savedCount}</strong></div><p class="muted">Android can isolate different downloaded content:// files. If an older download has data this file cannot see, export a Full Backup from the older file and import it here.</p></article></section><section class="card section"><div class="section-head"><div><span class="eyebrow">Data</span><h2>Import and export</h2></div></div><div class="inline"><button class="btn btn-primary" data-action="export-backup">Export Everything</button><button class="btn" data-action="import-backup">Import Package</button>${latestRestore ? `<button class="btn" data-action="undo-import" data-id="${escapeHtml(latestRestore.id)}">Undo latest import</button>` : ""}</div><p class="muted">Normal packages are blueprints. A Full Backup carries the complete factual state through its export timestamp.</p></section><section class="card danger-zone section"><div class="section-head"><div><span class="eyebrow">Safety</span><h2>Bin</h2><p class="muted">Deleted definitions remain recoverable for ten days. Restoring a definition does not reopen cancelled Runs or skipped Occurrences.</p></div><span class="badge">${bin.length} items</span></div>${binRows}</section></main>`;
}
